// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

type GetLinkInfoRequest struct {
	Domain *string `queryParam:"style=form,explode=true,name=domain"`
	// The key of the link to retrieve. E.g. for `d.to/github`, the key is `github`.
	Key *string `queryParam:"style=form,explode=true,name=key"`
	// The unique ID of the short link.
	ID string `queryParam:"style=form,explode=true,name=linkId"`
	// This is the ID of the link in the your database.
	ExternalID *string `queryParam:"style=form,explode=true,name=externalId"`
}

func (g *GetLinkInfoRequest) GetDomain() *string {
	if g == nil {
		return nil
	}
	return g.Domain
}

func (g *GetLinkInfoRequest) GetKey() *string {
	if g == nil {
		return nil
	}
	return g.Key
}

func (g *GetLinkInfoRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetLinkInfoRequest) GetExternalID() *string {
	if g == nil {
		return nil
	}
	return g.ExternalID
}

type GetLinkInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The retrieved link
	LinkSchema *shared.LinkSchema
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (g *GetLinkInfoResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetLinkInfoResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetLinkInfoResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetLinkInfoResponse) GetLinkSchema() *shared.LinkSchema {
	if g == nil {
		return nil
	}
	return g.LinkSchema
}

func (g *GetLinkInfoResponse) GetFourHundred() *shared.FourHundred {
	if g == nil {
		return nil
	}
	return g.FourHundred
}

func (g *GetLinkInfoResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if g == nil {
		return nil
	}
	return g.FourHundredAndOne
}

func (g *GetLinkInfoResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if g == nil {
		return nil
	}
	return g.FourHundredAndThree
}

func (g *GetLinkInfoResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if g == nil {
		return nil
	}
	return g.FourHundredAndFour
}

func (g *GetLinkInfoResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if g == nil {
		return nil
	}
	return g.FourHundredAndNine
}

func (g *GetLinkInfoResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if g == nil {
		return nil
	}
	return g.FourHundredAndTen
}

func (g *GetLinkInfoResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if g == nil {
		return nil
	}
	return g.FourHundredAndTwentyTwo
}

func (g *GetLinkInfoResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if g == nil {
		return nil
	}
	return g.FourHundredAndTwentyNine
}

func (g *GetLinkInfoResponse) GetFiveHundred() *shared.FiveHundred {
	if g == nil {
		return nil
	}
	return g.FiveHundred
}
