// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/internal/utils"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

// SortBy - The field to sort the tags by.
type SortBy string

const (
	SortByName      SortBy = "name"
	SortByCreatedAt SortBy = "createdAt"
)

func (e SortBy) ToPointer() *SortBy {
	return &e
}
func (e *SortBy) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "name":
		fallthrough
	case "createdAt":
		*e = SortBy(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SortBy: %v", v)
	}
}

// SortOrder - The order to sort the tags by.
type SortOrder string

const (
	SortOrderAsc  SortOrder = "asc"
	SortOrderDesc SortOrder = "desc"
)

func (e SortOrder) ToPointer() *SortOrder {
	return &e
}
func (e *SortOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "asc":
		fallthrough
	case "desc":
		*e = SortOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SortOrder: %v", v)
	}
}

type IdsType string

const (
	IdsTypeStr        IdsType = "str"
	IdsTypeArrayOfStr IdsType = "arrayOfStr"
)

// Ids - IDs of tags to filter by.
type Ids struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type IdsType
}

func CreateIdsStr(str string) Ids {
	typ := IdsTypeStr

	return Ids{
		Str:  &str,
		Type: typ,
	}
}

func CreateIdsArrayOfStr(arrayOfStr []string) Ids {
	typ := IdsTypeArrayOfStr

	return Ids{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *Ids) UnmarshalJSON(data []byte) (err error) {
	previous := *u
	*u = Ids{}
	defer func() {
		if err != nil {
			*u = previous
		}
	}()

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IdsTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  IdsTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Ids", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for Ids", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(IdsType)
	switch best.Type {
	case IdsTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case IdsTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for Ids", string(data))
}

func (u Ids) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type Ids: all fields are null")
}

type GetTagsRequest struct {
	// The field to sort the tags by.
	SortBy *SortBy `default:"name" queryParam:"style=form,explode=true,name=sortBy"`
	// The order to sort the tags by.
	SortOrder *SortOrder `default:"asc" queryParam:"style=form,explode=true,name=sortOrder"`
	// The search term to filter the tags by.
	Search *string `queryParam:"style=form,explode=true,name=search"`
	// IDs of tags to filter by.
	Ids *Ids `queryParam:"style=form,explode=true,name=ids"`
	// The page number for pagination.
	Page *float64 `default:"1" queryParam:"style=form,explode=true,name=page"`
	// The number of items per page.
	PageSize *float64 `default:"100" queryParam:"style=form,explode=true,name=pageSize"`
}

func (g GetTagsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetTagsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetTagsRequest) GetSortBy() *SortBy {
	if g == nil {
		return nil
	}
	return g.SortBy
}

func (g *GetTagsRequest) GetSortOrder() *SortOrder {
	if g == nil {
		return nil
	}
	return g.SortOrder
}

func (g *GetTagsRequest) GetSearch() *string {
	if g == nil {
		return nil
	}
	return g.Search
}

func (g *GetTagsRequest) GetIds() *Ids {
	if g == nil {
		return nil
	}
	return g.Ids
}

func (g *GetTagsRequest) GetPage() *float64 {
	if g == nil {
		return nil
	}
	return g.Page
}

func (g *GetTagsRequest) GetPageSize() *float64 {
	if g == nil {
		return nil
	}
	return g.PageSize
}

type GetTagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// A list of tags
	TagSchemas []shared.TagSchema
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (g *GetTagsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetTagsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetTagsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetTagsResponse) GetTagSchemas() []shared.TagSchema {
	if g == nil {
		return nil
	}
	return g.TagSchemas
}

func (g *GetTagsResponse) GetFourHundred() *shared.FourHundred {
	if g == nil {
		return nil
	}
	return g.FourHundred
}

func (g *GetTagsResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if g == nil {
		return nil
	}
	return g.FourHundredAndOne
}

func (g *GetTagsResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if g == nil {
		return nil
	}
	return g.FourHundredAndThree
}

func (g *GetTagsResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if g == nil {
		return nil
	}
	return g.FourHundredAndFour
}

func (g *GetTagsResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if g == nil {
		return nil
	}
	return g.FourHundredAndNine
}

func (g *GetTagsResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if g == nil {
		return nil
	}
	return g.FourHundredAndTen
}

func (g *GetTagsResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if g == nil {
		return nil
	}
	return g.FourHundredAndTwentyTwo
}

func (g *GetTagsResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if g == nil {
		return nil
	}
	return g.FourHundredAndTwentyNine
}

func (g *GetTagsResponse) GetFiveHundred() *shared.FiveHundred {
	if g == nil {
		return nil
	}
	return g.FiveHundred
}
