// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"errors"
	"fmt"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/internal/utils"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

type UpdateLinkTagIdsType string

const (
	UpdateLinkTagIdsTypeStr        UpdateLinkTagIdsType = "str"
	UpdateLinkTagIdsTypeArrayOfStr UpdateLinkTagIdsType = "arrayOfStr"
)

// UpdateLinkTagIds - The unique IDs of the tags assigned to the short link.
type UpdateLinkTagIds struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type UpdateLinkTagIdsType
}

func CreateUpdateLinkTagIdsStr(str string) UpdateLinkTagIds {
	typ := UpdateLinkTagIdsTypeStr

	return UpdateLinkTagIds{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpdateLinkTagIdsArrayOfStr(arrayOfStr []string) UpdateLinkTagIds {
	typ := UpdateLinkTagIdsTypeArrayOfStr

	return UpdateLinkTagIds{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *UpdateLinkTagIds) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateLinkTagIdsTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateLinkTagIdsTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateLinkTagIds", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateLinkTagIds", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateLinkTagIdsType)
	switch best.Type {
	case UpdateLinkTagIdsTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case UpdateLinkTagIdsTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateLinkTagIds", string(data))
}

func (u UpdateLinkTagIds) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateLinkTagIds: all fields are null")
}

type UpdateLinkTagNamesType string

const (
	UpdateLinkTagNamesTypeStr        UpdateLinkTagNamesType = "str"
	UpdateLinkTagNamesTypeArrayOfStr UpdateLinkTagNamesType = "arrayOfStr"
)

// UpdateLinkTagNames - The unique name of the tags assigned to the short link (case insensitive).
type UpdateLinkTagNames struct {
	Str        *string  `queryParam:"inline" union:"member"`
	ArrayOfStr []string `queryParam:"inline" union:"member"`

	Type UpdateLinkTagNamesType
}

func CreateUpdateLinkTagNamesStr(str string) UpdateLinkTagNames {
	typ := UpdateLinkTagNamesTypeStr

	return UpdateLinkTagNames{
		Str:  &str,
		Type: typ,
	}
}

func CreateUpdateLinkTagNamesArrayOfStr(arrayOfStr []string) UpdateLinkTagNames {
	typ := UpdateLinkTagNamesTypeArrayOfStr

	return UpdateLinkTagNames{
		ArrayOfStr: arrayOfStr,
		Type:       typ,
	}
}

func (u *UpdateLinkTagNames) UnmarshalJSON(data []byte) error {

	var candidates []utils.UnionCandidate

	// Collect all valid candidates
	var str string = ""
	if err := utils.UnmarshalJSON(data, &str, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateLinkTagNamesTypeStr,
			Value: &str,
		})
	}

	var arrayOfStr []string = []string{}
	if err := utils.UnmarshalJSON(data, &arrayOfStr, "", true, nil); err == nil {
		candidates = append(candidates, utils.UnionCandidate{
			Type:  UpdateLinkTagNamesTypeArrayOfStr,
			Value: arrayOfStr,
		})
	}

	if len(candidates) == 0 {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateLinkTagNames", string(data))
	}

	// Pick the best candidate using multi-stage filtering
	best := utils.PickBestUnionCandidate(candidates, data)
	if best == nil {
		return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateLinkTagNames", string(data))
	}

	// Set the union type and value based on the best candidate
	u.Type = best.Type.(UpdateLinkTagNamesType)
	switch best.Type {
	case UpdateLinkTagNamesTypeStr:
		u.Str = best.Value.(*string)
		return nil
	case UpdateLinkTagNamesTypeArrayOfStr:
		u.ArrayOfStr = best.Value.([]string)
		return nil
	}

	return fmt.Errorf("could not unmarshal `%s` into any supported union types for UpdateLinkTagNames", string(data))
}

func (u UpdateLinkTagNames) MarshalJSON() ([]byte, error) {
	if u.Str != nil {
		return utils.MarshalJSON(u.Str, "", true)
	}

	if u.ArrayOfStr != nil {
		return utils.MarshalJSON(u.ArrayOfStr, "", true)
	}

	return nil, errors.New("could not marshal union type UpdateLinkTagNames: all fields are null")
}

type UpdateLinkTestVariant struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (u *UpdateLinkTestVariant) GetURL() string {
	if u == nil {
		return ""
	}
	return u.URL
}

func (u *UpdateLinkTestVariant) GetPercentage() float64 {
	if u == nil {
		return 0.0
	}
	return u.Percentage
}

type UpdateLinkRequestBody struct {
	// The destination URL of the short link.
	URL *string `json:"url,omitempty"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain *string `json:"domain,omitempty"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key *string `json:"key,omitempty"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId,omitempty"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId,omitempty"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId,omitempty"`
	// The ID of the partner the short link is associated with.
	PartnerID *string `json:"partnerId,omitempty"`
	// Whether to track conversions for the short link. Defaults to `false` if not provided.
	TrackConversion *bool `json:"trackConversion,omitempty"`
	// Whether the short link is archived. Defaults to `false` if not provided.
	Archived *bool `json:"archived,omitempty"`
	// Deprecated: Use `dashboard` instead. Whether the short link's stats are publicly accessible. Defaults to `false` if not provided.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	PublicStats *bool `json:"publicStats,omitempty"`
	// The unique ID of the tag assigned to the short link. This field is deprecated – use `tagIds` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId,omitempty"`
	// The unique IDs of the tags assigned to the short link.
	TagIds *UpdateLinkTagIds `json:"tagIds,omitempty"`
	// The unique name of the tags assigned to the short link (case insensitive).
	TagNames *UpdateLinkTagNames `json:"tagNames,omitempty"`
	// The unique ID existing folder to assign the short link to.
	FolderID *string `json:"folderId,omitempty"`
	// The comments for the short link.
	Comments *string `json:"comments,omitempty"`
	// The date and time when the short link will expire at.
	ExpiresAt *string `json:"expiresAt,omitempty"`
	// The URL to redirect to when the short link has expired.
	ExpiredURL *string `json:"expiredUrl,omitempty"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password,omitempty"`
	// Whether the short link uses Custom Link Previews feature. Defaults to `false` if not provided.
	Proxy *bool `json:"proxy,omitempty"`
	// The custom link preview title (og:title). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Title *string `json:"title,omitempty"`
	// The custom link preview description (og:description). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Description *string `json:"description,omitempty"`
	Image       *string `json:"image,omitempty"`
	// The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Video *string `json:"video,omitempty"`
	// Whether the short link uses link cloaking. Defaults to `false` if not provided.
	Rewrite *bool `json:"rewrite,omitempty"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios,omitempty"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android,omitempty"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`.
	Geo *shared.LinkGeoTargeting `json:"geo,omitempty"`
	// Allow search engines to index your short link. Defaults to `false` if not provided. Learn more: https://d.to/noindex
	DoIndex *bool `json:"doIndex,omitempty"`
	// The UTM source of the short link. If set, this will populate or override the UTM source in the destination URL.
	UtmSource *string `json:"utm_source,omitempty"`
	// The UTM medium of the short link. If set, this will populate or override the UTM medium in the destination URL.
	UtmMedium *string `json:"utm_medium,omitempty"`
	// The UTM campaign of the short link. If set, this will populate or override the UTM campaign in the destination URL.
	UtmCampaign *string `json:"utm_campaign,omitempty"`
	// The UTM term of the short link. If set, this will populate or override the UTM term in the destination URL.
	UtmTerm *string `json:"utm_term,omitempty"`
	// The UTM content of the short link. If set, this will populate or override the UTM content in the destination URL.
	UtmContent *string `json:"utm_content,omitempty"`
	// The referral tag of the short link. If set, this will populate or override the `ref` query parameter in the destination URL.
	Ref *string `json:"ref,omitempty"`
	// An array of webhook IDs to trigger when the link is clicked. These webhooks will receive click event data.
	WebhookIds []string `json:"webhookIds,omitempty"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants []UpdateLinkTestVariant `json:"testVariants,omitempty"`
	// The date and time when the tests started.
	TestStartedAt *string `json:"testStartedAt,omitempty"`
	// The date and time when the tests were or will be completed.
	TestCompletedAt *string `json:"testCompletedAt,omitempty"`
}

func (u *UpdateLinkRequestBody) GetURL() *string {
	if u == nil {
		return nil
	}
	return u.URL
}

func (u *UpdateLinkRequestBody) GetDomain() *string {
	if u == nil {
		return nil
	}
	return u.Domain
}

func (u *UpdateLinkRequestBody) GetKey() *string {
	if u == nil {
		return nil
	}
	return u.Key
}

func (u *UpdateLinkRequestBody) GetExternalID() *string {
	if u == nil {
		return nil
	}
	return u.ExternalID
}

func (u *UpdateLinkRequestBody) GetTenantID() *string {
	if u == nil {
		return nil
	}
	return u.TenantID
}

func (u *UpdateLinkRequestBody) GetProgramID() *string {
	if u == nil {
		return nil
	}
	return u.ProgramID
}

func (u *UpdateLinkRequestBody) GetPartnerID() *string {
	if u == nil {
		return nil
	}
	return u.PartnerID
}

func (u *UpdateLinkRequestBody) GetTrackConversion() *bool {
	if u == nil {
		return nil
	}
	return u.TrackConversion
}

func (u *UpdateLinkRequestBody) GetArchived() *bool {
	if u == nil {
		return nil
	}
	return u.Archived
}

func (u *UpdateLinkRequestBody) GetPublicStats() *bool {
	if u == nil {
		return nil
	}
	return u.PublicStats
}

func (u *UpdateLinkRequestBody) GetTagID() *string {
	if u == nil {
		return nil
	}
	return u.TagID
}

func (u *UpdateLinkRequestBody) GetTagIds() *UpdateLinkTagIds {
	if u == nil {
		return nil
	}
	return u.TagIds
}

func (u *UpdateLinkRequestBody) GetTagNames() *UpdateLinkTagNames {
	if u == nil {
		return nil
	}
	return u.TagNames
}

func (u *UpdateLinkRequestBody) GetFolderID() *string {
	if u == nil {
		return nil
	}
	return u.FolderID
}

func (u *UpdateLinkRequestBody) GetComments() *string {
	if u == nil {
		return nil
	}
	return u.Comments
}

func (u *UpdateLinkRequestBody) GetExpiresAt() *string {
	if u == nil {
		return nil
	}
	return u.ExpiresAt
}

func (u *UpdateLinkRequestBody) GetExpiredURL() *string {
	if u == nil {
		return nil
	}
	return u.ExpiredURL
}

func (u *UpdateLinkRequestBody) GetPassword() *string {
	if u == nil {
		return nil
	}
	return u.Password
}

func (u *UpdateLinkRequestBody) GetProxy() *bool {
	if u == nil {
		return nil
	}
	return u.Proxy
}

func (u *UpdateLinkRequestBody) GetTitle() *string {
	if u == nil {
		return nil
	}
	return u.Title
}

func (u *UpdateLinkRequestBody) GetDescription() *string {
	if u == nil {
		return nil
	}
	return u.Description
}

func (u *UpdateLinkRequestBody) GetImage() *string {
	if u == nil {
		return nil
	}
	return u.Image
}

func (u *UpdateLinkRequestBody) GetVideo() *string {
	if u == nil {
		return nil
	}
	return u.Video
}

func (u *UpdateLinkRequestBody) GetRewrite() *bool {
	if u == nil {
		return nil
	}
	return u.Rewrite
}

func (u *UpdateLinkRequestBody) GetIos() *string {
	if u == nil {
		return nil
	}
	return u.Ios
}

func (u *UpdateLinkRequestBody) GetAndroid() *string {
	if u == nil {
		return nil
	}
	return u.Android
}

func (u *UpdateLinkRequestBody) GetGeo() *shared.LinkGeoTargeting {
	if u == nil {
		return nil
	}
	return u.Geo
}

func (u *UpdateLinkRequestBody) GetDoIndex() *bool {
	if u == nil {
		return nil
	}
	return u.DoIndex
}

func (u *UpdateLinkRequestBody) GetUtmSource() *string {
	if u == nil {
		return nil
	}
	return u.UtmSource
}

func (u *UpdateLinkRequestBody) GetUtmMedium() *string {
	if u == nil {
		return nil
	}
	return u.UtmMedium
}

func (u *UpdateLinkRequestBody) GetUtmCampaign() *string {
	if u == nil {
		return nil
	}
	return u.UtmCampaign
}

func (u *UpdateLinkRequestBody) GetUtmTerm() *string {
	if u == nil {
		return nil
	}
	return u.UtmTerm
}

func (u *UpdateLinkRequestBody) GetUtmContent() *string {
	if u == nil {
		return nil
	}
	return u.UtmContent
}

func (u *UpdateLinkRequestBody) GetRef() *string {
	if u == nil {
		return nil
	}
	return u.Ref
}

func (u *UpdateLinkRequestBody) GetWebhookIds() []string {
	if u == nil {
		return nil
	}
	return u.WebhookIds
}

func (u *UpdateLinkRequestBody) GetTestVariants() []UpdateLinkTestVariant {
	if u == nil {
		return nil
	}
	return u.TestVariants
}

func (u *UpdateLinkRequestBody) GetTestStartedAt() *string {
	if u == nil {
		return nil
	}
	return u.TestStartedAt
}

func (u *UpdateLinkRequestBody) GetTestCompletedAt() *string {
	if u == nil {
		return nil
	}
	return u.TestCompletedAt
}

type UpdateLinkRequest struct {
	// The id of the link to update. You may use either `linkId` (obtained via `/links/info` endpoint) or `externalId` prefixed with `ext_`.
	ID          string                 `pathParam:"style=simple,explode=false,name=linkId"`
	RequestBody *UpdateLinkRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateLinkRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateLinkRequest) GetRequestBody() *UpdateLinkRequestBody {
	if u == nil {
		return nil
	}
	return u.RequestBody
}

type UpdateLinkResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The updated link
	LinkSchema *shared.LinkSchema
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (u *UpdateLinkResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateLinkResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateLinkResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateLinkResponse) GetLinkSchema() *shared.LinkSchema {
	if u == nil {
		return nil
	}
	return u.LinkSchema
}

func (u *UpdateLinkResponse) GetFourHundred() *shared.FourHundred {
	if u == nil {
		return nil
	}
	return u.FourHundred
}

func (u *UpdateLinkResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if u == nil {
		return nil
	}
	return u.FourHundredAndOne
}

func (u *UpdateLinkResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if u == nil {
		return nil
	}
	return u.FourHundredAndThree
}

func (u *UpdateLinkResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if u == nil {
		return nil
	}
	return u.FourHundredAndFour
}

func (u *UpdateLinkResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if u == nil {
		return nil
	}
	return u.FourHundredAndNine
}

func (u *UpdateLinkResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if u == nil {
		return nil
	}
	return u.FourHundredAndTen
}

func (u *UpdateLinkResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if u == nil {
		return nil
	}
	return u.FourHundredAndTwentyTwo
}

func (u *UpdateLinkResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if u == nil {
		return nil
	}
	return u.FourHundredAndTwentyNine
}

func (u *UpdateLinkResponse) GetFiveHundred() *shared.FiveHundred {
	if u == nil {
		return nil
	}
	return u.FiveHundred
}
