// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/models/shared"
	"net/http"
)

// UpdateTagColor - The color of the tag. If not provided, a random color will be used from the list: red, yellow, green, blue, purple, pink, brown.
type UpdateTagColor string

const (
	UpdateTagColorRed    UpdateTagColor = "red"
	UpdateTagColorYellow UpdateTagColor = "yellow"
	UpdateTagColorGreen  UpdateTagColor = "green"
	UpdateTagColorBlue   UpdateTagColor = "blue"
	UpdateTagColorPurple UpdateTagColor = "purple"
	UpdateTagColorPink   UpdateTagColor = "pink"
	UpdateTagColorBrown  UpdateTagColor = "brown"
)

func (e UpdateTagColor) ToPointer() *UpdateTagColor {
	return &e
}
func (e *UpdateTagColor) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "red":
		fallthrough
	case "yellow":
		fallthrough
	case "green":
		fallthrough
	case "blue":
		fallthrough
	case "purple":
		fallthrough
	case "pink":
		fallthrough
	case "brown":
		*e = UpdateTagColor(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UpdateTagColor: %v", v)
	}
}

type UpdateTagRequestBody struct {
	// The name of the tag to create.
	Name *string `json:"name,omitempty"`
	// The color of the tag. If not provided, a random color will be used from the list: red, yellow, green, blue, purple, pink, brown.
	Color *UpdateTagColor `json:"color,omitempty"`
	// The name of the tag to create.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Tag *string `json:"tag,omitempty"`
}

func (u *UpdateTagRequestBody) GetName() *string {
	if u == nil {
		return nil
	}
	return u.Name
}

func (u *UpdateTagRequestBody) GetColor() *UpdateTagColor {
	if u == nil {
		return nil
	}
	return u.Color
}

func (u *UpdateTagRequestBody) GetTag() *string {
	if u == nil {
		return nil
	}
	return u.Tag
}

type UpdateTagRequest struct {
	// The ID of the tag to update.
	ID          string                `pathParam:"style=simple,explode=false,name=id"`
	RequestBody *UpdateTagRequestBody `request:"mediaType=application/json"`
}

func (u *UpdateTagRequest) GetID() string {
	if u == nil {
		return ""
	}
	return u.ID
}

func (u *UpdateTagRequest) GetRequestBody() *UpdateTagRequestBody {
	if u == nil {
		return nil
	}
	return u.RequestBody
}

type UpdateTagResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The updated tag.
	TagSchema *shared.TagSchema
	// The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
	FourHundred *shared.FourHundred
	// Although the HTTP standard specifies "unauthorized", semantically this response means "unauthenticated". That is, the client must authenticate itself to get the requested response.
	FourHundredAndOne *shared.FourHundredAndOne
	// The client does not have access rights to the content; that is, it is unauthorized, so the server is refusing to give the requested resource. Unlike 401 Unauthorized, the client's identity is known to the server.
	FourHundredAndThree *shared.FourHundredAndThree
	// The server cannot find the requested resource.
	FourHundredAndFour *shared.FourHundredAndFour
	// This response is sent when a request conflicts with the current state of the server.
	FourHundredAndNine *shared.FourHundredAndNine
	// This response is sent when the requested content has been permanently deleted from server, with no forwarding address.
	FourHundredAndTen *shared.FourHundredAndTen
	// The request was well-formed but was unable to be followed due to semantic errors.
	FourHundredAndTwentyTwo *shared.FourHundredAndTwentyTwo
	// The user has sent too many requests in a given amount of time ("rate limiting")
	FourHundredAndTwentyNine *shared.FourHundredAndTwentyNine
	// The server has encountered a situation it does not know how to handle.
	FiveHundred *shared.FiveHundred
}

func (u *UpdateTagResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateTagResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateTagResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateTagResponse) GetTagSchema() *shared.TagSchema {
	if u == nil {
		return nil
	}
	return u.TagSchema
}

func (u *UpdateTagResponse) GetFourHundred() *shared.FourHundred {
	if u == nil {
		return nil
	}
	return u.FourHundred
}

func (u *UpdateTagResponse) GetFourHundredAndOne() *shared.FourHundredAndOne {
	if u == nil {
		return nil
	}
	return u.FourHundredAndOne
}

func (u *UpdateTagResponse) GetFourHundredAndThree() *shared.FourHundredAndThree {
	if u == nil {
		return nil
	}
	return u.FourHundredAndThree
}

func (u *UpdateTagResponse) GetFourHundredAndFour() *shared.FourHundredAndFour {
	if u == nil {
		return nil
	}
	return u.FourHundredAndFour
}

func (u *UpdateTagResponse) GetFourHundredAndNine() *shared.FourHundredAndNine {
	if u == nil {
		return nil
	}
	return u.FourHundredAndNine
}

func (u *UpdateTagResponse) GetFourHundredAndTen() *shared.FourHundredAndTen {
	if u == nil {
		return nil
	}
	return u.FourHundredAndTen
}

func (u *UpdateTagResponse) GetFourHundredAndTwentyTwo() *shared.FourHundredAndTwentyTwo {
	if u == nil {
		return nil
	}
	return u.FourHundredAndTwentyTwo
}

func (u *UpdateTagResponse) GetFourHundredAndTwentyNine() *shared.FourHundredAndTwentyNine {
	if u == nil {
		return nil
	}
	return u.FourHundredAndTwentyNine
}

func (u *UpdateTagResponse) GetFiveHundred() *shared.FiveHundred {
	if u == nil {
		return nil
	}
	return u.FiveHundred
}
