// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FourHundredAndTwentyNineCode - A short code indicating the error code returned.
type FourHundredAndTwentyNineCode string

const (
	FourHundredAndTwentyNineCodeRateLimitExceeded FourHundredAndTwentyNineCode = "rate_limit_exceeded"
)

func (e FourHundredAndTwentyNineCode) ToPointer() *FourHundredAndTwentyNineCode {
	return &e
}
func (e *FourHundredAndTwentyNineCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "rate_limit_exceeded":
		*e = FourHundredAndTwentyNineCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FourHundredAndTwentyNineCode: %v", v)
	}
}

type FourHundredAndTwentyNineError struct {
	// A short code indicating the error code returned.
	Code FourHundredAndTwentyNineCode `json:"code"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
}

func (f *FourHundredAndTwentyNineError) GetCode() FourHundredAndTwentyNineCode {
	if f == nil {
		return FourHundredAndTwentyNineCode("")
	}
	return f.Code
}

func (f *FourHundredAndTwentyNineError) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}

func (f *FourHundredAndTwentyNineError) GetDocURL() *string {
	if f == nil {
		return nil
	}
	return f.DocURL
}

// FourHundredAndTwentyNine - The user has sent too many requests in a given amount of time ("rate limiting")
type FourHundredAndTwentyNine struct {
	Error FourHundredAndTwentyNineError `json:"error"`
}

func (f *FourHundredAndTwentyNine) GetError() FourHundredAndTwentyNineError {
	if f == nil {
		return FourHundredAndTwentyNineError{}
	}
	return f.Error
}
