// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FourHundredAndNineCode - A short code indicating the error code returned.
type FourHundredAndNineCode string

const (
	FourHundredAndNineCodeConflict FourHundredAndNineCode = "conflict"
)

func (e FourHundredAndNineCode) ToPointer() *FourHundredAndNineCode {
	return &e
}
func (e *FourHundredAndNineCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "conflict":
		*e = FourHundredAndNineCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FourHundredAndNineCode: %v", v)
	}
}

type FourHundredAndNineError struct {
	// A short code indicating the error code returned.
	Code FourHundredAndNineCode `json:"code"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
}

func (f *FourHundredAndNineError) GetCode() FourHundredAndNineCode {
	if f == nil {
		return FourHundredAndNineCode("")
	}
	return f.Code
}

func (f *FourHundredAndNineError) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}

func (f *FourHundredAndNineError) GetDocURL() *string {
	if f == nil {
		return nil
	}
	return f.DocURL
}

// FourHundredAndNine - This response is sent when a request conflicts with the current state of the server.
type FourHundredAndNine struct {
	Error FourHundredAndNineError `json:"error"`
}

func (f *FourHundredAndNine) GetError() FourHundredAndNineError {
	if f == nil {
		return FourHundredAndNineError{}
	}
	return f.Error
}
