// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// FourHundredAndTwentyTwoCode - A short code indicating the error code returned.
type FourHundredAndTwentyTwoCode string

const (
	FourHundredAndTwentyTwoCodeUnprocessableEntity FourHundredAndTwentyTwoCode = "unprocessable_entity"
)

func (e FourHundredAndTwentyTwoCode) ToPointer() *FourHundredAndTwentyTwoCode {
	return &e
}
func (e *FourHundredAndTwentyTwoCode) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "unprocessable_entity":
		*e = FourHundredAndTwentyTwoCode(v)
		return nil
	default:
		return fmt.Errorf("invalid value for FourHundredAndTwentyTwoCode: %v", v)
	}
}

type FourHundredAndTwentyTwoError struct {
	// A short code indicating the error code returned.
	Code FourHundredAndTwentyTwoCode `json:"code"`
	// A human readable explanation of what went wrong.
	Message string `json:"message"`
	// A link to our documentation with more details about this error code
	DocURL *string `json:"doc_url,omitempty"`
}

func (f *FourHundredAndTwentyTwoError) GetCode() FourHundredAndTwentyTwoCode {
	if f == nil {
		return FourHundredAndTwentyTwoCode("")
	}
	return f.Code
}

func (f *FourHundredAndTwentyTwoError) GetMessage() string {
	if f == nil {
		return ""
	}
	return f.Message
}

func (f *FourHundredAndTwentyTwoError) GetDocURL() *string {
	if f == nil {
		return nil
	}
	return f.DocURL
}

// FourHundredAndTwentyTwo - The request was well-formed but was unable to be followed due to semantic errors.
type FourHundredAndTwentyTwo struct {
	Error FourHundredAndTwentyTwoError `json:"error"`
}

func (f *FourHundredAndTwentyTwo) GetError() FourHundredAndTwentyTwoError {
	if f == nil {
		return FourHundredAndTwentyTwoError{}
	}
	return f.Error
}
