// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/ryan-blunden/terraform-provider-dub/internal/sdk/internal/utils"
)

// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo
type Geo struct {
	Af *string `json:"AF,omitempty"`
	Al *string `json:"AL,omitempty"`
	Dz *string `json:"DZ,omitempty"`
	As *string `json:"AS,omitempty"`
	Ad *string `json:"AD,omitempty"`
	Ao *string `json:"AO,omitempty"`
	Ai *string `json:"AI,omitempty"`
	Aq *string `json:"AQ,omitempty"`
	Ag *string `json:"AG,omitempty"`
	Ar *string `json:"AR,omitempty"`
	Am *string `json:"AM,omitempty"`
	Aw *string `json:"AW,omitempty"`
	Au *string `json:"AU,omitempty"`
	At *string `json:"AT,omitempty"`
	Az *string `json:"AZ,omitempty"`
	Bs *string `json:"BS,omitempty"`
	Bh *string `json:"BH,omitempty"`
	Bd *string `json:"BD,omitempty"`
	Bb *string `json:"BB,omitempty"`
	By *string `json:"BY,omitempty"`
	Be *string `json:"BE,omitempty"`
	Bz *string `json:"BZ,omitempty"`
	Bj *string `json:"BJ,omitempty"`
	Bm *string `json:"BM,omitempty"`
	Bt *string `json:"BT,omitempty"`
	Bo *string `json:"BO,omitempty"`
	Ba *string `json:"BA,omitempty"`
	Bw *string `json:"BW,omitempty"`
	Bv *string `json:"BV,omitempty"`
	Br *string `json:"BR,omitempty"`
	Io *string `json:"IO,omitempty"`
	Bn *string `json:"BN,omitempty"`
	Bg *string `json:"BG,omitempty"`
	Bf *string `json:"BF,omitempty"`
	Bi *string `json:"BI,omitempty"`
	Kh *string `json:"KH,omitempty"`
	Cm *string `json:"CM,omitempty"`
	Ca *string `json:"CA,omitempty"`
	Cv *string `json:"CV,omitempty"`
	Ky *string `json:"KY,omitempty"`
	Cf *string `json:"CF,omitempty"`
	Td *string `json:"TD,omitempty"`
	Cl *string `json:"CL,omitempty"`
	Cn *string `json:"CN,omitempty"`
	Cx *string `json:"CX,omitempty"`
	Cc *string `json:"CC,omitempty"`
	Co *string `json:"CO,omitempty"`
	Km *string `json:"KM,omitempty"`
	Cg *string `json:"CG,omitempty"`
	Cd *string `json:"CD,omitempty"`
	Ck *string `json:"CK,omitempty"`
	Cr *string `json:"CR,omitempty"`
	Ci *string `json:"CI,omitempty"`
	Hr *string `json:"HR,omitempty"`
	Cu *string `json:"CU,omitempty"`
	Cy *string `json:"CY,omitempty"`
	Cz *string `json:"CZ,omitempty"`
	Dk *string `json:"DK,omitempty"`
	Dj *string `json:"DJ,omitempty"`
	Dm *string `json:"DM,omitempty"`
	Do *string `json:"DO,omitempty"`
	Ec *string `json:"EC,omitempty"`
	Eg *string `json:"EG,omitempty"`
	Sv *string `json:"SV,omitempty"`
	Gq *string `json:"GQ,omitempty"`
	Er *string `json:"ER,omitempty"`
	Ee *string `json:"EE,omitempty"`
	Et *string `json:"ET,omitempty"`
	Fk *string `json:"FK,omitempty"`
	Fo *string `json:"FO,omitempty"`
	Fj *string `json:"FJ,omitempty"`
	Fi *string `json:"FI,omitempty"`
	Fr *string `json:"FR,omitempty"`
	Gf *string `json:"GF,omitempty"`
	Pf *string `json:"PF,omitempty"`
	Tf *string `json:"TF,omitempty"`
	Ga *string `json:"GA,omitempty"`
	Gm *string `json:"GM,omitempty"`
	Ge *string `json:"GE,omitempty"`
	De *string `json:"DE,omitempty"`
	Gh *string `json:"GH,omitempty"`
	Gi *string `json:"GI,omitempty"`
	Gr *string `json:"GR,omitempty"`
	Gl *string `json:"GL,omitempty"`
	Gd *string `json:"GD,omitempty"`
	Gp *string `json:"GP,omitempty"`
	Gu *string `json:"GU,omitempty"`
	Gt *string `json:"GT,omitempty"`
	Gn *string `json:"GN,omitempty"`
	Gw *string `json:"GW,omitempty"`
	Gy *string `json:"GY,omitempty"`
	Ht *string `json:"HT,omitempty"`
	Hm *string `json:"HM,omitempty"`
	Va *string `json:"VA,omitempty"`
	Hn *string `json:"HN,omitempty"`
	Hk *string `json:"HK,omitempty"`
	Hu *string `json:"HU,omitempty"`
	Is *string `json:"IS,omitempty"`
	In *string `json:"IN,omitempty"`
	ID *string `json:"ID,omitempty"`
	Ir *string `json:"IR,omitempty"`
	Iq *string `json:"IQ,omitempty"`
	Ie *string `json:"IE,omitempty"`
	Il *string `json:"IL,omitempty"`
	It *string `json:"IT,omitempty"`
	Jm *string `json:"JM,omitempty"`
	Jp *string `json:"JP,omitempty"`
	Jo *string `json:"JO,omitempty"`
	Kz *string `json:"KZ,omitempty"`
	Ke *string `json:"KE,omitempty"`
	Ki *string `json:"KI,omitempty"`
	Kp *string `json:"KP,omitempty"`
	Kr *string `json:"KR,omitempty"`
	Kw *string `json:"KW,omitempty"`
	Kg *string `json:"KG,omitempty"`
	La *string `json:"LA,omitempty"`
	Lv *string `json:"LV,omitempty"`
	Lb *string `json:"LB,omitempty"`
	Ls *string `json:"LS,omitempty"`
	Lr *string `json:"LR,omitempty"`
	Ly *string `json:"LY,omitempty"`
	Li *string `json:"LI,omitempty"`
	Lt *string `json:"LT,omitempty"`
	Lu *string `json:"LU,omitempty"`
	Mo *string `json:"MO,omitempty"`
	Mg *string `json:"MG,omitempty"`
	Mw *string `json:"MW,omitempty"`
	My *string `json:"MY,omitempty"`
	Mv *string `json:"MV,omitempty"`
	Ml *string `json:"ML,omitempty"`
	Mt *string `json:"MT,omitempty"`
	Mh *string `json:"MH,omitempty"`
	Mq *string `json:"MQ,omitempty"`
	Mr *string `json:"MR,omitempty"`
	Mu *string `json:"MU,omitempty"`
	Yt *string `json:"YT,omitempty"`
	Mx *string `json:"MX,omitempty"`
	Fm *string `json:"FM,omitempty"`
	Md *string `json:"MD,omitempty"`
	Mc *string `json:"MC,omitempty"`
	Mn *string `json:"MN,omitempty"`
	Ms *string `json:"MS,omitempty"`
	Ma *string `json:"MA,omitempty"`
	Mz *string `json:"MZ,omitempty"`
	Mm *string `json:"MM,omitempty"`
	Na *string `json:"NA,omitempty"`
	Nr *string `json:"NR,omitempty"`
	Np *string `json:"NP,omitempty"`
	Nl *string `json:"NL,omitempty"`
	Nc *string `json:"NC,omitempty"`
	Nz *string `json:"NZ,omitempty"`
	Ni *string `json:"NI,omitempty"`
	Ne *string `json:"NE,omitempty"`
	Ng *string `json:"NG,omitempty"`
	Nu *string `json:"NU,omitempty"`
	Nf *string `json:"NF,omitempty"`
	Mk *string `json:"MK,omitempty"`
	Mp *string `json:"MP,omitempty"`
	No *string `json:"NO,omitempty"`
	Om *string `json:"OM,omitempty"`
	Pk *string `json:"PK,omitempty"`
	Pw *string `json:"PW,omitempty"`
	Ps *string `json:"PS,omitempty"`
	Pa *string `json:"PA,omitempty"`
	Pg *string `json:"PG,omitempty"`
	Py *string `json:"PY,omitempty"`
	Pe *string `json:"PE,omitempty"`
	Ph *string `json:"PH,omitempty"`
	Pn *string `json:"PN,omitempty"`
	Pl *string `json:"PL,omitempty"`
	Pt *string `json:"PT,omitempty"`
	Pr *string `json:"PR,omitempty"`
	Qa *string `json:"QA,omitempty"`
	Re *string `json:"RE,omitempty"`
	Ro *string `json:"RO,omitempty"`
	Ru *string `json:"RU,omitempty"`
	Rw *string `json:"RW,omitempty"`
	Sh *string `json:"SH,omitempty"`
	Kn *string `json:"KN,omitempty"`
	Lc *string `json:"LC,omitempty"`
	Pm *string `json:"PM,omitempty"`
	Vc *string `json:"VC,omitempty"`
	Ws *string `json:"WS,omitempty"`
	Sm *string `json:"SM,omitempty"`
	St *string `json:"ST,omitempty"`
	Sa *string `json:"SA,omitempty"`
	Sn *string `json:"SN,omitempty"`
	Sc *string `json:"SC,omitempty"`
	Sl *string `json:"SL,omitempty"`
	Sg *string `json:"SG,omitempty"`
	Sk *string `json:"SK,omitempty"`
	Si *string `json:"SI,omitempty"`
	Sb *string `json:"SB,omitempty"`
	So *string `json:"SO,omitempty"`
	Za *string `json:"ZA,omitempty"`
	Gs *string `json:"GS,omitempty"`
	Es *string `json:"ES,omitempty"`
	Lk *string `json:"LK,omitempty"`
	Sd *string `json:"SD,omitempty"`
	Sr *string `json:"SR,omitempty"`
	Sj *string `json:"SJ,omitempty"`
	Sz *string `json:"SZ,omitempty"`
	Se *string `json:"SE,omitempty"`
	Ch *string `json:"CH,omitempty"`
	Sy *string `json:"SY,omitempty"`
	Tw *string `json:"TW,omitempty"`
	Tj *string `json:"TJ,omitempty"`
	Tz *string `json:"TZ,omitempty"`
	Th *string `json:"TH,omitempty"`
	Tl *string `json:"TL,omitempty"`
	Tg *string `json:"TG,omitempty"`
	Tk *string `json:"TK,omitempty"`
	To *string `json:"TO,omitempty"`
	Tt *string `json:"TT,omitempty"`
	Tn *string `json:"TN,omitempty"`
	Tr *string `json:"TR,omitempty"`
	Tm *string `json:"TM,omitempty"`
	Tc *string `json:"TC,omitempty"`
	Tv *string `json:"TV,omitempty"`
	Ug *string `json:"UG,omitempty"`
	Ua *string `json:"UA,omitempty"`
	Ae *string `json:"AE,omitempty"`
	Gb *string `json:"GB,omitempty"`
	Us *string `json:"US,omitempty"`
	Um *string `json:"UM,omitempty"`
	Uy *string `json:"UY,omitempty"`
	Uz *string `json:"UZ,omitempty"`
	Vu *string `json:"VU,omitempty"`
	Ve *string `json:"VE,omitempty"`
	Vn *string `json:"VN,omitempty"`
	Vg *string `json:"VG,omitempty"`
	Vi *string `json:"VI,omitempty"`
	Wf *string `json:"WF,omitempty"`
	Eh *string `json:"EH,omitempty"`
	Ye *string `json:"YE,omitempty"`
	Zm *string `json:"ZM,omitempty"`
	Zw *string `json:"ZW,omitempty"`
	Ax *string `json:"AX,omitempty"`
	Bq *string `json:"BQ,omitempty"`
	Cw *string `json:"CW,omitempty"`
	Gg *string `json:"GG,omitempty"`
	Im *string `json:"IM,omitempty"`
	Je *string `json:"JE,omitempty"`
	Me *string `json:"ME,omitempty"`
	Bl *string `json:"BL,omitempty"`
	Mf *string `json:"MF,omitempty"`
	Rs *string `json:"RS,omitempty"`
	Sx *string `json:"SX,omitempty"`
	Ss *string `json:"SS,omitempty"`
	Xk *string `json:"XK,omitempty"`
}

func (g *Geo) GetAf() *string {
	if g == nil {
		return nil
	}
	return g.Af
}

func (g *Geo) GetAl() *string {
	if g == nil {
		return nil
	}
	return g.Al
}

func (g *Geo) GetDz() *string {
	if g == nil {
		return nil
	}
	return g.Dz
}

func (g *Geo) GetAs() *string {
	if g == nil {
		return nil
	}
	return g.As
}

func (g *Geo) GetAd() *string {
	if g == nil {
		return nil
	}
	return g.Ad
}

func (g *Geo) GetAo() *string {
	if g == nil {
		return nil
	}
	return g.Ao
}

func (g *Geo) GetAi() *string {
	if g == nil {
		return nil
	}
	return g.Ai
}

func (g *Geo) GetAq() *string {
	if g == nil {
		return nil
	}
	return g.Aq
}

func (g *Geo) GetAg() *string {
	if g == nil {
		return nil
	}
	return g.Ag
}

func (g *Geo) GetAr() *string {
	if g == nil {
		return nil
	}
	return g.Ar
}

func (g *Geo) GetAm() *string {
	if g == nil {
		return nil
	}
	return g.Am
}

func (g *Geo) GetAw() *string {
	if g == nil {
		return nil
	}
	return g.Aw
}

func (g *Geo) GetAu() *string {
	if g == nil {
		return nil
	}
	return g.Au
}

func (g *Geo) GetAt() *string {
	if g == nil {
		return nil
	}
	return g.At
}

func (g *Geo) GetAz() *string {
	if g == nil {
		return nil
	}
	return g.Az
}

func (g *Geo) GetBs() *string {
	if g == nil {
		return nil
	}
	return g.Bs
}

func (g *Geo) GetBh() *string {
	if g == nil {
		return nil
	}
	return g.Bh
}

func (g *Geo) GetBd() *string {
	if g == nil {
		return nil
	}
	return g.Bd
}

func (g *Geo) GetBb() *string {
	if g == nil {
		return nil
	}
	return g.Bb
}

func (g *Geo) GetBy() *string {
	if g == nil {
		return nil
	}
	return g.By
}

func (g *Geo) GetBe() *string {
	if g == nil {
		return nil
	}
	return g.Be
}

func (g *Geo) GetBz() *string {
	if g == nil {
		return nil
	}
	return g.Bz
}

func (g *Geo) GetBj() *string {
	if g == nil {
		return nil
	}
	return g.Bj
}

func (g *Geo) GetBm() *string {
	if g == nil {
		return nil
	}
	return g.Bm
}

func (g *Geo) GetBt() *string {
	if g == nil {
		return nil
	}
	return g.Bt
}

func (g *Geo) GetBo() *string {
	if g == nil {
		return nil
	}
	return g.Bo
}

func (g *Geo) GetBa() *string {
	if g == nil {
		return nil
	}
	return g.Ba
}

func (g *Geo) GetBw() *string {
	if g == nil {
		return nil
	}
	return g.Bw
}

func (g *Geo) GetBv() *string {
	if g == nil {
		return nil
	}
	return g.Bv
}

func (g *Geo) GetBr() *string {
	if g == nil {
		return nil
	}
	return g.Br
}

func (g *Geo) GetIo() *string {
	if g == nil {
		return nil
	}
	return g.Io
}

func (g *Geo) GetBn() *string {
	if g == nil {
		return nil
	}
	return g.Bn
}

func (g *Geo) GetBg() *string {
	if g == nil {
		return nil
	}
	return g.Bg
}

func (g *Geo) GetBf() *string {
	if g == nil {
		return nil
	}
	return g.Bf
}

func (g *Geo) GetBi() *string {
	if g == nil {
		return nil
	}
	return g.Bi
}

func (g *Geo) GetKh() *string {
	if g == nil {
		return nil
	}
	return g.Kh
}

func (g *Geo) GetCm() *string {
	if g == nil {
		return nil
	}
	return g.Cm
}

func (g *Geo) GetCa() *string {
	if g == nil {
		return nil
	}
	return g.Ca
}

func (g *Geo) GetCv() *string {
	if g == nil {
		return nil
	}
	return g.Cv
}

func (g *Geo) GetKy() *string {
	if g == nil {
		return nil
	}
	return g.Ky
}

func (g *Geo) GetCf() *string {
	if g == nil {
		return nil
	}
	return g.Cf
}

func (g *Geo) GetTd() *string {
	if g == nil {
		return nil
	}
	return g.Td
}

func (g *Geo) GetCl() *string {
	if g == nil {
		return nil
	}
	return g.Cl
}

func (g *Geo) GetCn() *string {
	if g == nil {
		return nil
	}
	return g.Cn
}

func (g *Geo) GetCx() *string {
	if g == nil {
		return nil
	}
	return g.Cx
}

func (g *Geo) GetCc() *string {
	if g == nil {
		return nil
	}
	return g.Cc
}

func (g *Geo) GetCo() *string {
	if g == nil {
		return nil
	}
	return g.Co
}

func (g *Geo) GetKm() *string {
	if g == nil {
		return nil
	}
	return g.Km
}

func (g *Geo) GetCg() *string {
	if g == nil {
		return nil
	}
	return g.Cg
}

func (g *Geo) GetCd() *string {
	if g == nil {
		return nil
	}
	return g.Cd
}

func (g *Geo) GetCk() *string {
	if g == nil {
		return nil
	}
	return g.Ck
}

func (g *Geo) GetCr() *string {
	if g == nil {
		return nil
	}
	return g.Cr
}

func (g *Geo) GetCi() *string {
	if g == nil {
		return nil
	}
	return g.Ci
}

func (g *Geo) GetHr() *string {
	if g == nil {
		return nil
	}
	return g.Hr
}

func (g *Geo) GetCu() *string {
	if g == nil {
		return nil
	}
	return g.Cu
}

func (g *Geo) GetCy() *string {
	if g == nil {
		return nil
	}
	return g.Cy
}

func (g *Geo) GetCz() *string {
	if g == nil {
		return nil
	}
	return g.Cz
}

func (g *Geo) GetDk() *string {
	if g == nil {
		return nil
	}
	return g.Dk
}

func (g *Geo) GetDj() *string {
	if g == nil {
		return nil
	}
	return g.Dj
}

func (g *Geo) GetDm() *string {
	if g == nil {
		return nil
	}
	return g.Dm
}

func (g *Geo) GetDo() *string {
	if g == nil {
		return nil
	}
	return g.Do
}

func (g *Geo) GetEc() *string {
	if g == nil {
		return nil
	}
	return g.Ec
}

func (g *Geo) GetEg() *string {
	if g == nil {
		return nil
	}
	return g.Eg
}

func (g *Geo) GetSv() *string {
	if g == nil {
		return nil
	}
	return g.Sv
}

func (g *Geo) GetGq() *string {
	if g == nil {
		return nil
	}
	return g.Gq
}

func (g *Geo) GetEr() *string {
	if g == nil {
		return nil
	}
	return g.Er
}

func (g *Geo) GetEe() *string {
	if g == nil {
		return nil
	}
	return g.Ee
}

func (g *Geo) GetEt() *string {
	if g == nil {
		return nil
	}
	return g.Et
}

func (g *Geo) GetFk() *string {
	if g == nil {
		return nil
	}
	return g.Fk
}

func (g *Geo) GetFo() *string {
	if g == nil {
		return nil
	}
	return g.Fo
}

func (g *Geo) GetFj() *string {
	if g == nil {
		return nil
	}
	return g.Fj
}

func (g *Geo) GetFi() *string {
	if g == nil {
		return nil
	}
	return g.Fi
}

func (g *Geo) GetFr() *string {
	if g == nil {
		return nil
	}
	return g.Fr
}

func (g *Geo) GetGf() *string {
	if g == nil {
		return nil
	}
	return g.Gf
}

func (g *Geo) GetPf() *string {
	if g == nil {
		return nil
	}
	return g.Pf
}

func (g *Geo) GetTf() *string {
	if g == nil {
		return nil
	}
	return g.Tf
}

func (g *Geo) GetGa() *string {
	if g == nil {
		return nil
	}
	return g.Ga
}

func (g *Geo) GetGm() *string {
	if g == nil {
		return nil
	}
	return g.Gm
}

func (g *Geo) GetGe() *string {
	if g == nil {
		return nil
	}
	return g.Ge
}

func (g *Geo) GetDe() *string {
	if g == nil {
		return nil
	}
	return g.De
}

func (g *Geo) GetGh() *string {
	if g == nil {
		return nil
	}
	return g.Gh
}

func (g *Geo) GetGi() *string {
	if g == nil {
		return nil
	}
	return g.Gi
}

func (g *Geo) GetGr() *string {
	if g == nil {
		return nil
	}
	return g.Gr
}

func (g *Geo) GetGl() *string {
	if g == nil {
		return nil
	}
	return g.Gl
}

func (g *Geo) GetGd() *string {
	if g == nil {
		return nil
	}
	return g.Gd
}

func (g *Geo) GetGp() *string {
	if g == nil {
		return nil
	}
	return g.Gp
}

func (g *Geo) GetGu() *string {
	if g == nil {
		return nil
	}
	return g.Gu
}

func (g *Geo) GetGt() *string {
	if g == nil {
		return nil
	}
	return g.Gt
}

func (g *Geo) GetGn() *string {
	if g == nil {
		return nil
	}
	return g.Gn
}

func (g *Geo) GetGw() *string {
	if g == nil {
		return nil
	}
	return g.Gw
}

func (g *Geo) GetGy() *string {
	if g == nil {
		return nil
	}
	return g.Gy
}

func (g *Geo) GetHt() *string {
	if g == nil {
		return nil
	}
	return g.Ht
}

func (g *Geo) GetHm() *string {
	if g == nil {
		return nil
	}
	return g.Hm
}

func (g *Geo) GetVa() *string {
	if g == nil {
		return nil
	}
	return g.Va
}

func (g *Geo) GetHn() *string {
	if g == nil {
		return nil
	}
	return g.Hn
}

func (g *Geo) GetHk() *string {
	if g == nil {
		return nil
	}
	return g.Hk
}

func (g *Geo) GetHu() *string {
	if g == nil {
		return nil
	}
	return g.Hu
}

func (g *Geo) GetIs() *string {
	if g == nil {
		return nil
	}
	return g.Is
}

func (g *Geo) GetIn() *string {
	if g == nil {
		return nil
	}
	return g.In
}

func (g *Geo) GetID() *string {
	if g == nil {
		return nil
	}
	return g.ID
}

func (g *Geo) GetIr() *string {
	if g == nil {
		return nil
	}
	return g.Ir
}

func (g *Geo) GetIq() *string {
	if g == nil {
		return nil
	}
	return g.Iq
}

func (g *Geo) GetIe() *string {
	if g == nil {
		return nil
	}
	return g.Ie
}

func (g *Geo) GetIl() *string {
	if g == nil {
		return nil
	}
	return g.Il
}

func (g *Geo) GetIt() *string {
	if g == nil {
		return nil
	}
	return g.It
}

func (g *Geo) GetJm() *string {
	if g == nil {
		return nil
	}
	return g.Jm
}

func (g *Geo) GetJp() *string {
	if g == nil {
		return nil
	}
	return g.Jp
}

func (g *Geo) GetJo() *string {
	if g == nil {
		return nil
	}
	return g.Jo
}

func (g *Geo) GetKz() *string {
	if g == nil {
		return nil
	}
	return g.Kz
}

func (g *Geo) GetKe() *string {
	if g == nil {
		return nil
	}
	return g.Ke
}

func (g *Geo) GetKi() *string {
	if g == nil {
		return nil
	}
	return g.Ki
}

func (g *Geo) GetKp() *string {
	if g == nil {
		return nil
	}
	return g.Kp
}

func (g *Geo) GetKr() *string {
	if g == nil {
		return nil
	}
	return g.Kr
}

func (g *Geo) GetKw() *string {
	if g == nil {
		return nil
	}
	return g.Kw
}

func (g *Geo) GetKg() *string {
	if g == nil {
		return nil
	}
	return g.Kg
}

func (g *Geo) GetLa() *string {
	if g == nil {
		return nil
	}
	return g.La
}

func (g *Geo) GetLv() *string {
	if g == nil {
		return nil
	}
	return g.Lv
}

func (g *Geo) GetLb() *string {
	if g == nil {
		return nil
	}
	return g.Lb
}

func (g *Geo) GetLs() *string {
	if g == nil {
		return nil
	}
	return g.Ls
}

func (g *Geo) GetLr() *string {
	if g == nil {
		return nil
	}
	return g.Lr
}

func (g *Geo) GetLy() *string {
	if g == nil {
		return nil
	}
	return g.Ly
}

func (g *Geo) GetLi() *string {
	if g == nil {
		return nil
	}
	return g.Li
}

func (g *Geo) GetLt() *string {
	if g == nil {
		return nil
	}
	return g.Lt
}

func (g *Geo) GetLu() *string {
	if g == nil {
		return nil
	}
	return g.Lu
}

func (g *Geo) GetMo() *string {
	if g == nil {
		return nil
	}
	return g.Mo
}

func (g *Geo) GetMg() *string {
	if g == nil {
		return nil
	}
	return g.Mg
}

func (g *Geo) GetMw() *string {
	if g == nil {
		return nil
	}
	return g.Mw
}

func (g *Geo) GetMy() *string {
	if g == nil {
		return nil
	}
	return g.My
}

func (g *Geo) GetMv() *string {
	if g == nil {
		return nil
	}
	return g.Mv
}

func (g *Geo) GetMl() *string {
	if g == nil {
		return nil
	}
	return g.Ml
}

func (g *Geo) GetMt() *string {
	if g == nil {
		return nil
	}
	return g.Mt
}

func (g *Geo) GetMh() *string {
	if g == nil {
		return nil
	}
	return g.Mh
}

func (g *Geo) GetMq() *string {
	if g == nil {
		return nil
	}
	return g.Mq
}

func (g *Geo) GetMr() *string {
	if g == nil {
		return nil
	}
	return g.Mr
}

func (g *Geo) GetMu() *string {
	if g == nil {
		return nil
	}
	return g.Mu
}

func (g *Geo) GetYt() *string {
	if g == nil {
		return nil
	}
	return g.Yt
}

func (g *Geo) GetMx() *string {
	if g == nil {
		return nil
	}
	return g.Mx
}

func (g *Geo) GetFm() *string {
	if g == nil {
		return nil
	}
	return g.Fm
}

func (g *Geo) GetMd() *string {
	if g == nil {
		return nil
	}
	return g.Md
}

func (g *Geo) GetMc() *string {
	if g == nil {
		return nil
	}
	return g.Mc
}

func (g *Geo) GetMn() *string {
	if g == nil {
		return nil
	}
	return g.Mn
}

func (g *Geo) GetMs() *string {
	if g == nil {
		return nil
	}
	return g.Ms
}

func (g *Geo) GetMa() *string {
	if g == nil {
		return nil
	}
	return g.Ma
}

func (g *Geo) GetMz() *string {
	if g == nil {
		return nil
	}
	return g.Mz
}

func (g *Geo) GetMm() *string {
	if g == nil {
		return nil
	}
	return g.Mm
}

func (g *Geo) GetNa() *string {
	if g == nil {
		return nil
	}
	return g.Na
}

func (g *Geo) GetNr() *string {
	if g == nil {
		return nil
	}
	return g.Nr
}

func (g *Geo) GetNp() *string {
	if g == nil {
		return nil
	}
	return g.Np
}

func (g *Geo) GetNl() *string {
	if g == nil {
		return nil
	}
	return g.Nl
}

func (g *Geo) GetNc() *string {
	if g == nil {
		return nil
	}
	return g.Nc
}

func (g *Geo) GetNz() *string {
	if g == nil {
		return nil
	}
	return g.Nz
}

func (g *Geo) GetNi() *string {
	if g == nil {
		return nil
	}
	return g.Ni
}

func (g *Geo) GetNe() *string {
	if g == nil {
		return nil
	}
	return g.Ne
}

func (g *Geo) GetNg() *string {
	if g == nil {
		return nil
	}
	return g.Ng
}

func (g *Geo) GetNu() *string {
	if g == nil {
		return nil
	}
	return g.Nu
}

func (g *Geo) GetNf() *string {
	if g == nil {
		return nil
	}
	return g.Nf
}

func (g *Geo) GetMk() *string {
	if g == nil {
		return nil
	}
	return g.Mk
}

func (g *Geo) GetMp() *string {
	if g == nil {
		return nil
	}
	return g.Mp
}

func (g *Geo) GetNo() *string {
	if g == nil {
		return nil
	}
	return g.No
}

func (g *Geo) GetOm() *string {
	if g == nil {
		return nil
	}
	return g.Om
}

func (g *Geo) GetPk() *string {
	if g == nil {
		return nil
	}
	return g.Pk
}

func (g *Geo) GetPw() *string {
	if g == nil {
		return nil
	}
	return g.Pw
}

func (g *Geo) GetPs() *string {
	if g == nil {
		return nil
	}
	return g.Ps
}

func (g *Geo) GetPa() *string {
	if g == nil {
		return nil
	}
	return g.Pa
}

func (g *Geo) GetPg() *string {
	if g == nil {
		return nil
	}
	return g.Pg
}

func (g *Geo) GetPy() *string {
	if g == nil {
		return nil
	}
	return g.Py
}

func (g *Geo) GetPe() *string {
	if g == nil {
		return nil
	}
	return g.Pe
}

func (g *Geo) GetPh() *string {
	if g == nil {
		return nil
	}
	return g.Ph
}

func (g *Geo) GetPn() *string {
	if g == nil {
		return nil
	}
	return g.Pn
}

func (g *Geo) GetPl() *string {
	if g == nil {
		return nil
	}
	return g.Pl
}

func (g *Geo) GetPt() *string {
	if g == nil {
		return nil
	}
	return g.Pt
}

func (g *Geo) GetPr() *string {
	if g == nil {
		return nil
	}
	return g.Pr
}

func (g *Geo) GetQa() *string {
	if g == nil {
		return nil
	}
	return g.Qa
}

func (g *Geo) GetRe() *string {
	if g == nil {
		return nil
	}
	return g.Re
}

func (g *Geo) GetRo() *string {
	if g == nil {
		return nil
	}
	return g.Ro
}

func (g *Geo) GetRu() *string {
	if g == nil {
		return nil
	}
	return g.Ru
}

func (g *Geo) GetRw() *string {
	if g == nil {
		return nil
	}
	return g.Rw
}

func (g *Geo) GetSh() *string {
	if g == nil {
		return nil
	}
	return g.Sh
}

func (g *Geo) GetKn() *string {
	if g == nil {
		return nil
	}
	return g.Kn
}

func (g *Geo) GetLc() *string {
	if g == nil {
		return nil
	}
	return g.Lc
}

func (g *Geo) GetPm() *string {
	if g == nil {
		return nil
	}
	return g.Pm
}

func (g *Geo) GetVc() *string {
	if g == nil {
		return nil
	}
	return g.Vc
}

func (g *Geo) GetWs() *string {
	if g == nil {
		return nil
	}
	return g.Ws
}

func (g *Geo) GetSm() *string {
	if g == nil {
		return nil
	}
	return g.Sm
}

func (g *Geo) GetSt() *string {
	if g == nil {
		return nil
	}
	return g.St
}

func (g *Geo) GetSa() *string {
	if g == nil {
		return nil
	}
	return g.Sa
}

func (g *Geo) GetSn() *string {
	if g == nil {
		return nil
	}
	return g.Sn
}

func (g *Geo) GetSc() *string {
	if g == nil {
		return nil
	}
	return g.Sc
}

func (g *Geo) GetSl() *string {
	if g == nil {
		return nil
	}
	return g.Sl
}

func (g *Geo) GetSg() *string {
	if g == nil {
		return nil
	}
	return g.Sg
}

func (g *Geo) GetSk() *string {
	if g == nil {
		return nil
	}
	return g.Sk
}

func (g *Geo) GetSi() *string {
	if g == nil {
		return nil
	}
	return g.Si
}

func (g *Geo) GetSb() *string {
	if g == nil {
		return nil
	}
	return g.Sb
}

func (g *Geo) GetSo() *string {
	if g == nil {
		return nil
	}
	return g.So
}

func (g *Geo) GetZa() *string {
	if g == nil {
		return nil
	}
	return g.Za
}

func (g *Geo) GetGs() *string {
	if g == nil {
		return nil
	}
	return g.Gs
}

func (g *Geo) GetEs() *string {
	if g == nil {
		return nil
	}
	return g.Es
}

func (g *Geo) GetLk() *string {
	if g == nil {
		return nil
	}
	return g.Lk
}

func (g *Geo) GetSd() *string {
	if g == nil {
		return nil
	}
	return g.Sd
}

func (g *Geo) GetSr() *string {
	if g == nil {
		return nil
	}
	return g.Sr
}

func (g *Geo) GetSj() *string {
	if g == nil {
		return nil
	}
	return g.Sj
}

func (g *Geo) GetSz() *string {
	if g == nil {
		return nil
	}
	return g.Sz
}

func (g *Geo) GetSe() *string {
	if g == nil {
		return nil
	}
	return g.Se
}

func (g *Geo) GetCh() *string {
	if g == nil {
		return nil
	}
	return g.Ch
}

func (g *Geo) GetSy() *string {
	if g == nil {
		return nil
	}
	return g.Sy
}

func (g *Geo) GetTw() *string {
	if g == nil {
		return nil
	}
	return g.Tw
}

func (g *Geo) GetTj() *string {
	if g == nil {
		return nil
	}
	return g.Tj
}

func (g *Geo) GetTz() *string {
	if g == nil {
		return nil
	}
	return g.Tz
}

func (g *Geo) GetTh() *string {
	if g == nil {
		return nil
	}
	return g.Th
}

func (g *Geo) GetTl() *string {
	if g == nil {
		return nil
	}
	return g.Tl
}

func (g *Geo) GetTg() *string {
	if g == nil {
		return nil
	}
	return g.Tg
}

func (g *Geo) GetTk() *string {
	if g == nil {
		return nil
	}
	return g.Tk
}

func (g *Geo) GetTo() *string {
	if g == nil {
		return nil
	}
	return g.To
}

func (g *Geo) GetTt() *string {
	if g == nil {
		return nil
	}
	return g.Tt
}

func (g *Geo) GetTn() *string {
	if g == nil {
		return nil
	}
	return g.Tn
}

func (g *Geo) GetTr() *string {
	if g == nil {
		return nil
	}
	return g.Tr
}

func (g *Geo) GetTm() *string {
	if g == nil {
		return nil
	}
	return g.Tm
}

func (g *Geo) GetTc() *string {
	if g == nil {
		return nil
	}
	return g.Tc
}

func (g *Geo) GetTv() *string {
	if g == nil {
		return nil
	}
	return g.Tv
}

func (g *Geo) GetUg() *string {
	if g == nil {
		return nil
	}
	return g.Ug
}

func (g *Geo) GetUa() *string {
	if g == nil {
		return nil
	}
	return g.Ua
}

func (g *Geo) GetAe() *string {
	if g == nil {
		return nil
	}
	return g.Ae
}

func (g *Geo) GetGb() *string {
	if g == nil {
		return nil
	}
	return g.Gb
}

func (g *Geo) GetUs() *string {
	if g == nil {
		return nil
	}
	return g.Us
}

func (g *Geo) GetUm() *string {
	if g == nil {
		return nil
	}
	return g.Um
}

func (g *Geo) GetUy() *string {
	if g == nil {
		return nil
	}
	return g.Uy
}

func (g *Geo) GetUz() *string {
	if g == nil {
		return nil
	}
	return g.Uz
}

func (g *Geo) GetVu() *string {
	if g == nil {
		return nil
	}
	return g.Vu
}

func (g *Geo) GetVe() *string {
	if g == nil {
		return nil
	}
	return g.Ve
}

func (g *Geo) GetVn() *string {
	if g == nil {
		return nil
	}
	return g.Vn
}

func (g *Geo) GetVg() *string {
	if g == nil {
		return nil
	}
	return g.Vg
}

func (g *Geo) GetVi() *string {
	if g == nil {
		return nil
	}
	return g.Vi
}

func (g *Geo) GetWf() *string {
	if g == nil {
		return nil
	}
	return g.Wf
}

func (g *Geo) GetEh() *string {
	if g == nil {
		return nil
	}
	return g.Eh
}

func (g *Geo) GetYe() *string {
	if g == nil {
		return nil
	}
	return g.Ye
}

func (g *Geo) GetZm() *string {
	if g == nil {
		return nil
	}
	return g.Zm
}

func (g *Geo) GetZw() *string {
	if g == nil {
		return nil
	}
	return g.Zw
}

func (g *Geo) GetAx() *string {
	if g == nil {
		return nil
	}
	return g.Ax
}

func (g *Geo) GetBq() *string {
	if g == nil {
		return nil
	}
	return g.Bq
}

func (g *Geo) GetCw() *string {
	if g == nil {
		return nil
	}
	return g.Cw
}

func (g *Geo) GetGg() *string {
	if g == nil {
		return nil
	}
	return g.Gg
}

func (g *Geo) GetIm() *string {
	if g == nil {
		return nil
	}
	return g.Im
}

func (g *Geo) GetJe() *string {
	if g == nil {
		return nil
	}
	return g.Je
}

func (g *Geo) GetMe() *string {
	if g == nil {
		return nil
	}
	return g.Me
}

func (g *Geo) GetBl() *string {
	if g == nil {
		return nil
	}
	return g.Bl
}

func (g *Geo) GetMf() *string {
	if g == nil {
		return nil
	}
	return g.Mf
}

func (g *Geo) GetRs() *string {
	if g == nil {
		return nil
	}
	return g.Rs
}

func (g *Geo) GetSx() *string {
	if g == nil {
		return nil
	}
	return g.Sx
}

func (g *Geo) GetSs() *string {
	if g == nil {
		return nil
	}
	return g.Ss
}

func (g *Geo) GetXk() *string {
	if g == nil {
		return nil
	}
	return g.Xk
}

type TestVariant struct {
	URL        string  `json:"url"`
	Percentage float64 `json:"percentage"`
}

func (t *TestVariant) GetURL() string {
	if t == nil {
		return ""
	}
	return t.URL
}

func (t *TestVariant) GetPercentage() float64 {
	if t == nil {
		return 0.0
	}
	return t.Percentage
}

type LinkSchema struct {
	// The unique ID of the short link.
	ID string `json:"id"`
	// The domain of the short link. If not provided, the primary domain for the workspace will be used (or `dub.sh` if the workspace has no domains).
	Domain string `json:"domain"`
	// The short link slug. If not provided, a random 7-character slug will be generated.
	Key string `json:"key"`
	// The destination URL of the short link.
	URL string `json:"url"`
	// Whether to track conversions for the short link.
	TrackConversion *bool `default:"false" json:"trackConversion"`
	// The ID of the link in your database. If set, it can be used to identify the link in future API requests (must be prefixed with 'ext_' when passed as a query parameter). This key is unique across your workspace.
	ExternalID *string `json:"externalId"`
	// The ID of the tenant that created the link inside your system. If set, it can be used to fetch all links for a tenant.
	TenantID *string `json:"tenantId"`
	// The ID of the program the short link is associated with.
	ProgramID *string `json:"programId"`
	// The ID of the partner the short link is associated with.
	PartnerID *string `json:"partnerId"`
	// Whether the short link is archived.
	Archived *bool `default:"false" json:"archived"`
	// The date and time when the short link will expire in ISO-8601 format.
	ExpiresAt *string `json:"expiresAt"`
	// The URL to redirect to when the short link has expired.
	ExpiredURL *string `json:"expiredUrl"`
	// The password required to access the destination URL of the short link.
	Password *string `json:"password"`
	// Whether the short link uses Custom Link Previews feature.
	Proxy *bool `default:"false" json:"proxy"`
	// The title of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Title *string `json:"title"`
	// The description of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Description *string `json:"description"`
	// The image of the short link. Will be used for Custom Link Previews if `proxy` is true.
	Image *string `json:"image"`
	// The custom link preview video (og:video). Will be used for Custom Link Previews if `proxy` is true. Learn more: https://d.to/og
	Video *string `json:"video"`
	// Whether the short link uses link cloaking.
	Rewrite *bool `default:"false" json:"rewrite"`
	// Whether to allow search engines to index the short link.
	DoIndex *bool `default:"false" json:"doIndex"`
	// The iOS destination URL for the short link for iOS device targeting.
	Ios *string `json:"ios"`
	// The Android destination URL for the short link for Android device targeting.
	Android *string `json:"android"`
	// Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`. Learn more: https://d.to/geo
	Geo *Geo `json:"geo"`
	// Whether the short link's stats are publicly accessible.
	PublicStats *bool `default:"false" json:"publicStats"`
	// The unique ID of the tag assigned to the short link. This field is deprecated – use `tags` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	TagID *string `json:"tagId"`
	// The tags assigned to the short link.
	Tags []TagSchema `json:"tags"`
	// The unique ID of the folder assigned to the short link.
	FolderID *string `json:"folderId"`
	// The IDs of the webhooks that the short link is associated with.
	WebhookIds []string `json:"webhookIds"`
	// The comments for the short link.
	Comments *string `json:"comments"`
	// The full URL of the short link, including the https protocol (e.g. `https://dub.sh/try`).
	ShortLink string `json:"shortLink"`
	// The full URL of the QR code for the short link (e.g. `https://api.dub.co/qr?url=https://dub.sh/try`).
	QrCode string `json:"qrCode"`
	// The UTM source of the short link.
	UtmSource *string `json:"utm_source"`
	// The UTM medium of the short link.
	UtmMedium *string `json:"utm_medium"`
	// The UTM campaign of the short link.
	UtmCampaign *string `json:"utm_campaign"`
	// The UTM term of the short link.
	UtmTerm *string `json:"utm_term"`
	// The UTM content of the short link.
	UtmContent *string `json:"utm_content"`
	// An array of A/B test URLs and the percentage of traffic to send to each URL.
	TestVariants []TestVariant `json:"testVariants,omitempty"`
	// The date and time when the tests started.
	TestStartedAt *string `json:"testStartedAt,omitempty"`
	// The date and time when the tests were or will be completed.
	TestCompletedAt *string `json:"testCompletedAt,omitempty"`
	// The user ID of the creator of the short link.
	UserID *string `json:"userId"`
	// The workspace ID of the short link.
	WorkspaceID string `json:"workspaceId"`
	// The number of clicks on the short link.
	Clicks *float64 `default:"0" json:"clicks"`
	// The date and time when the short link was last clicked.
	LastClicked *string `json:"lastClicked"`
	// The number of leads the short links has generated.
	Leads *float64 `default:"0" json:"leads"`
	// The number of sales the short links has generated.
	Sales *float64 `default:"0" json:"sales"`
	// The total dollar amount of sales the short links has generated (in cents).
	SaleAmount *float64 `default:"0" json:"saleAmount"`
	// The date and time when the short link was created.
	CreatedAt string `json:"createdAt"`
	// The date and time when the short link was last updated.
	UpdatedAt string `json:"updatedAt"`
	// The project ID of the short link. This field is deprecated – use `workspaceId` instead.
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	ProjectID  string  `json:"projectId"`
	Identifier *string `json:"identifier,omitempty"`
}

func (l LinkSchema) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LinkSchema) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LinkSchema) GetID() string {
	if l == nil {
		return ""
	}
	return l.ID
}

func (l *LinkSchema) GetDomain() string {
	if l == nil {
		return ""
	}
	return l.Domain
}

func (l *LinkSchema) GetKey() string {
	if l == nil {
		return ""
	}
	return l.Key
}

func (l *LinkSchema) GetURL() string {
	if l == nil {
		return ""
	}
	return l.URL
}

func (l *LinkSchema) GetTrackConversion() *bool {
	if l == nil {
		return nil
	}
	return l.TrackConversion
}

func (l *LinkSchema) GetExternalID() *string {
	if l == nil {
		return nil
	}
	return l.ExternalID
}

func (l *LinkSchema) GetTenantID() *string {
	if l == nil {
		return nil
	}
	return l.TenantID
}

func (l *LinkSchema) GetProgramID() *string {
	if l == nil {
		return nil
	}
	return l.ProgramID
}

func (l *LinkSchema) GetPartnerID() *string {
	if l == nil {
		return nil
	}
	return l.PartnerID
}

func (l *LinkSchema) GetArchived() *bool {
	if l == nil {
		return nil
	}
	return l.Archived
}

func (l *LinkSchema) GetExpiresAt() *string {
	if l == nil {
		return nil
	}
	return l.ExpiresAt
}

func (l *LinkSchema) GetExpiredURL() *string {
	if l == nil {
		return nil
	}
	return l.ExpiredURL
}

func (l *LinkSchema) GetPassword() *string {
	if l == nil {
		return nil
	}
	return l.Password
}

func (l *LinkSchema) GetProxy() *bool {
	if l == nil {
		return nil
	}
	return l.Proxy
}

func (l *LinkSchema) GetTitle() *string {
	if l == nil {
		return nil
	}
	return l.Title
}

func (l *LinkSchema) GetDescription() *string {
	if l == nil {
		return nil
	}
	return l.Description
}

func (l *LinkSchema) GetImage() *string {
	if l == nil {
		return nil
	}
	return l.Image
}

func (l *LinkSchema) GetVideo() *string {
	if l == nil {
		return nil
	}
	return l.Video
}

func (l *LinkSchema) GetRewrite() *bool {
	if l == nil {
		return nil
	}
	return l.Rewrite
}

func (l *LinkSchema) GetDoIndex() *bool {
	if l == nil {
		return nil
	}
	return l.DoIndex
}

func (l *LinkSchema) GetIos() *string {
	if l == nil {
		return nil
	}
	return l.Ios
}

func (l *LinkSchema) GetAndroid() *string {
	if l == nil {
		return nil
	}
	return l.Android
}

func (l *LinkSchema) GetGeo() *Geo {
	if l == nil {
		return nil
	}
	return l.Geo
}

func (l *LinkSchema) GetPublicStats() *bool {
	if l == nil {
		return nil
	}
	return l.PublicStats
}

func (l *LinkSchema) GetTagID() *string {
	if l == nil {
		return nil
	}
	return l.TagID
}

func (l *LinkSchema) GetTags() []TagSchema {
	if l == nil {
		return nil
	}
	return l.Tags
}

func (l *LinkSchema) GetFolderID() *string {
	if l == nil {
		return nil
	}
	return l.FolderID
}

func (l *LinkSchema) GetWebhookIds() []string {
	if l == nil {
		return []string{}
	}
	return l.WebhookIds
}

func (l *LinkSchema) GetComments() *string {
	if l == nil {
		return nil
	}
	return l.Comments
}

func (l *LinkSchema) GetShortLink() string {
	if l == nil {
		return ""
	}
	return l.ShortLink
}

func (l *LinkSchema) GetQrCode() string {
	if l == nil {
		return ""
	}
	return l.QrCode
}

func (l *LinkSchema) GetUtmSource() *string {
	if l == nil {
		return nil
	}
	return l.UtmSource
}

func (l *LinkSchema) GetUtmMedium() *string {
	if l == nil {
		return nil
	}
	return l.UtmMedium
}

func (l *LinkSchema) GetUtmCampaign() *string {
	if l == nil {
		return nil
	}
	return l.UtmCampaign
}

func (l *LinkSchema) GetUtmTerm() *string {
	if l == nil {
		return nil
	}
	return l.UtmTerm
}

func (l *LinkSchema) GetUtmContent() *string {
	if l == nil {
		return nil
	}
	return l.UtmContent
}

func (l *LinkSchema) GetTestVariants() []TestVariant {
	if l == nil {
		return nil
	}
	return l.TestVariants
}

func (l *LinkSchema) GetTestStartedAt() *string {
	if l == nil {
		return nil
	}
	return l.TestStartedAt
}

func (l *LinkSchema) GetTestCompletedAt() *string {
	if l == nil {
		return nil
	}
	return l.TestCompletedAt
}

func (l *LinkSchema) GetUserID() *string {
	if l == nil {
		return nil
	}
	return l.UserID
}

func (l *LinkSchema) GetWorkspaceID() string {
	if l == nil {
		return ""
	}
	return l.WorkspaceID
}

func (l *LinkSchema) GetClicks() *float64 {
	if l == nil {
		return nil
	}
	return l.Clicks
}

func (l *LinkSchema) GetLastClicked() *string {
	if l == nil {
		return nil
	}
	return l.LastClicked
}

func (l *LinkSchema) GetLeads() *float64 {
	if l == nil {
		return nil
	}
	return l.Leads
}

func (l *LinkSchema) GetSales() *float64 {
	if l == nil {
		return nil
	}
	return l.Sales
}

func (l *LinkSchema) GetSaleAmount() *float64 {
	if l == nil {
		return nil
	}
	return l.SaleAmount
}

func (l *LinkSchema) GetCreatedAt() string {
	if l == nil {
		return ""
	}
	return l.CreatedAt
}

func (l *LinkSchema) GetUpdatedAt() string {
	if l == nil {
		return ""
	}
	return l.UpdatedAt
}

func (l *LinkSchema) GetProjectID() string {
	if l == nil {
		return ""
	}
	return l.ProjectID
}

func (l *LinkSchema) GetIdentifier() *string {
	if l == nil {
		return nil
	}
	return l.Identifier
}
