// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// LinkGeoTargeting - Geo targeting information for the short link in JSON format `{[COUNTRY]: https://example.com }`.
type LinkGeoTargeting struct {
	Af *string `json:"AF,omitempty"`
	Al *string `json:"AL,omitempty"`
	Dz *string `json:"DZ,omitempty"`
	As *string `json:"AS,omitempty"`
	Ad *string `json:"AD,omitempty"`
	Ao *string `json:"AO,omitempty"`
	Ai *string `json:"AI,omitempty"`
	Aq *string `json:"AQ,omitempty"`
	Ag *string `json:"AG,omitempty"`
	Ar *string `json:"AR,omitempty"`
	Am *string `json:"AM,omitempty"`
	Aw *string `json:"AW,omitempty"`
	Au *string `json:"AU,omitempty"`
	At *string `json:"AT,omitempty"`
	Az *string `json:"AZ,omitempty"`
	Bs *string `json:"BS,omitempty"`
	Bh *string `json:"BH,omitempty"`
	Bd *string `json:"BD,omitempty"`
	Bb *string `json:"BB,omitempty"`
	By *string `json:"BY,omitempty"`
	Be *string `json:"BE,omitempty"`
	Bz *string `json:"BZ,omitempty"`
	Bj *string `json:"BJ,omitempty"`
	Bm *string `json:"BM,omitempty"`
	Bt *string `json:"BT,omitempty"`
	Bo *string `json:"BO,omitempty"`
	Ba *string `json:"BA,omitempty"`
	Bw *string `json:"BW,omitempty"`
	Bv *string `json:"BV,omitempty"`
	Br *string `json:"BR,omitempty"`
	Io *string `json:"IO,omitempty"`
	Bn *string `json:"BN,omitempty"`
	Bg *string `json:"BG,omitempty"`
	Bf *string `json:"BF,omitempty"`
	Bi *string `json:"BI,omitempty"`
	Kh *string `json:"KH,omitempty"`
	Cm *string `json:"CM,omitempty"`
	Ca *string `json:"CA,omitempty"`
	Cv *string `json:"CV,omitempty"`
	Ky *string `json:"KY,omitempty"`
	Cf *string `json:"CF,omitempty"`
	Td *string `json:"TD,omitempty"`
	Cl *string `json:"CL,omitempty"`
	Cn *string `json:"CN,omitempty"`
	Cx *string `json:"CX,omitempty"`
	Cc *string `json:"CC,omitempty"`
	Co *string `json:"CO,omitempty"`
	Km *string `json:"KM,omitempty"`
	Cg *string `json:"CG,omitempty"`
	Cd *string `json:"CD,omitempty"`
	Ck *string `json:"CK,omitempty"`
	Cr *string `json:"CR,omitempty"`
	Ci *string `json:"CI,omitempty"`
	Hr *string `json:"HR,omitempty"`
	Cu *string `json:"CU,omitempty"`
	Cy *string `json:"CY,omitempty"`
	Cz *string `json:"CZ,omitempty"`
	Dk *string `json:"DK,omitempty"`
	Dj *string `json:"DJ,omitempty"`
	Dm *string `json:"DM,omitempty"`
	Do *string `json:"DO,omitempty"`
	Ec *string `json:"EC,omitempty"`
	Eg *string `json:"EG,omitempty"`
	Sv *string `json:"SV,omitempty"`
	Gq *string `json:"GQ,omitempty"`
	Er *string `json:"ER,omitempty"`
	Ee *string `json:"EE,omitempty"`
	Et *string `json:"ET,omitempty"`
	Fk *string `json:"FK,omitempty"`
	Fo *string `json:"FO,omitempty"`
	Fj *string `json:"FJ,omitempty"`
	Fi *string `json:"FI,omitempty"`
	Fr *string `json:"FR,omitempty"`
	Gf *string `json:"GF,omitempty"`
	Pf *string `json:"PF,omitempty"`
	Tf *string `json:"TF,omitempty"`
	Ga *string `json:"GA,omitempty"`
	Gm *string `json:"GM,omitempty"`
	Ge *string `json:"GE,omitempty"`
	De *string `json:"DE,omitempty"`
	Gh *string `json:"GH,omitempty"`
	Gi *string `json:"GI,omitempty"`
	Gr *string `json:"GR,omitempty"`
	Gl *string `json:"GL,omitempty"`
	Gd *string `json:"GD,omitempty"`
	Gp *string `json:"GP,omitempty"`
	Gu *string `json:"GU,omitempty"`
	Gt *string `json:"GT,omitempty"`
	Gn *string `json:"GN,omitempty"`
	Gw *string `json:"GW,omitempty"`
	Gy *string `json:"GY,omitempty"`
	Ht *string `json:"HT,omitempty"`
	Hm *string `json:"HM,omitempty"`
	Va *string `json:"VA,omitempty"`
	Hn *string `json:"HN,omitempty"`
	Hk *string `json:"HK,omitempty"`
	Hu *string `json:"HU,omitempty"`
	Is *string `json:"IS,omitempty"`
	In *string `json:"IN,omitempty"`
	ID *string `json:"ID,omitempty"`
	Ir *string `json:"IR,omitempty"`
	Iq *string `json:"IQ,omitempty"`
	Ie *string `json:"IE,omitempty"`
	Il *string `json:"IL,omitempty"`
	It *string `json:"IT,omitempty"`
	Jm *string `json:"JM,omitempty"`
	Jp *string `json:"JP,omitempty"`
	Jo *string `json:"JO,omitempty"`
	Kz *string `json:"KZ,omitempty"`
	Ke *string `json:"KE,omitempty"`
	Ki *string `json:"KI,omitempty"`
	Kp *string `json:"KP,omitempty"`
	Kr *string `json:"KR,omitempty"`
	Kw *string `json:"KW,omitempty"`
	Kg *string `json:"KG,omitempty"`
	La *string `json:"LA,omitempty"`
	Lv *string `json:"LV,omitempty"`
	Lb *string `json:"LB,omitempty"`
	Ls *string `json:"LS,omitempty"`
	Lr *string `json:"LR,omitempty"`
	Ly *string `json:"LY,omitempty"`
	Li *string `json:"LI,omitempty"`
	Lt *string `json:"LT,omitempty"`
	Lu *string `json:"LU,omitempty"`
	Mo *string `json:"MO,omitempty"`
	Mg *string `json:"MG,omitempty"`
	Mw *string `json:"MW,omitempty"`
	My *string `json:"MY,omitempty"`
	Mv *string `json:"MV,omitempty"`
	Ml *string `json:"ML,omitempty"`
	Mt *string `json:"MT,omitempty"`
	Mh *string `json:"MH,omitempty"`
	Mq *string `json:"MQ,omitempty"`
	Mr *string `json:"MR,omitempty"`
	Mu *string `json:"MU,omitempty"`
	Yt *string `json:"YT,omitempty"`
	Mx *string `json:"MX,omitempty"`
	Fm *string `json:"FM,omitempty"`
	Md *string `json:"MD,omitempty"`
	Mc *string `json:"MC,omitempty"`
	Mn *string `json:"MN,omitempty"`
	Ms *string `json:"MS,omitempty"`
	Ma *string `json:"MA,omitempty"`
	Mz *string `json:"MZ,omitempty"`
	Mm *string `json:"MM,omitempty"`
	Na *string `json:"NA,omitempty"`
	Nr *string `json:"NR,omitempty"`
	Np *string `json:"NP,omitempty"`
	Nl *string `json:"NL,omitempty"`
	Nc *string `json:"NC,omitempty"`
	Nz *string `json:"NZ,omitempty"`
	Ni *string `json:"NI,omitempty"`
	Ne *string `json:"NE,omitempty"`
	Ng *string `json:"NG,omitempty"`
	Nu *string `json:"NU,omitempty"`
	Nf *string `json:"NF,omitempty"`
	Mk *string `json:"MK,omitempty"`
	Mp *string `json:"MP,omitempty"`
	No *string `json:"NO,omitempty"`
	Om *string `json:"OM,omitempty"`
	Pk *string `json:"PK,omitempty"`
	Pw *string `json:"PW,omitempty"`
	Ps *string `json:"PS,omitempty"`
	Pa *string `json:"PA,omitempty"`
	Pg *string `json:"PG,omitempty"`
	Py *string `json:"PY,omitempty"`
	Pe *string `json:"PE,omitempty"`
	Ph *string `json:"PH,omitempty"`
	Pn *string `json:"PN,omitempty"`
	Pl *string `json:"PL,omitempty"`
	Pt *string `json:"PT,omitempty"`
	Pr *string `json:"PR,omitempty"`
	Qa *string `json:"QA,omitempty"`
	Re *string `json:"RE,omitempty"`
	Ro *string `json:"RO,omitempty"`
	Ru *string `json:"RU,omitempty"`
	Rw *string `json:"RW,omitempty"`
	Sh *string `json:"SH,omitempty"`
	Kn *string `json:"KN,omitempty"`
	Lc *string `json:"LC,omitempty"`
	Pm *string `json:"PM,omitempty"`
	Vc *string `json:"VC,omitempty"`
	Ws *string `json:"WS,omitempty"`
	Sm *string `json:"SM,omitempty"`
	St *string `json:"ST,omitempty"`
	Sa *string `json:"SA,omitempty"`
	Sn *string `json:"SN,omitempty"`
	Sc *string `json:"SC,omitempty"`
	Sl *string `json:"SL,omitempty"`
	Sg *string `json:"SG,omitempty"`
	Sk *string `json:"SK,omitempty"`
	Si *string `json:"SI,omitempty"`
	Sb *string `json:"SB,omitempty"`
	So *string `json:"SO,omitempty"`
	Za *string `json:"ZA,omitempty"`
	Gs *string `json:"GS,omitempty"`
	Es *string `json:"ES,omitempty"`
	Lk *string `json:"LK,omitempty"`
	Sd *string `json:"SD,omitempty"`
	Sr *string `json:"SR,omitempty"`
	Sj *string `json:"SJ,omitempty"`
	Sz *string `json:"SZ,omitempty"`
	Se *string `json:"SE,omitempty"`
	Ch *string `json:"CH,omitempty"`
	Sy *string `json:"SY,omitempty"`
	Tw *string `json:"TW,omitempty"`
	Tj *string `json:"TJ,omitempty"`
	Tz *string `json:"TZ,omitempty"`
	Th *string `json:"TH,omitempty"`
	Tl *string `json:"TL,omitempty"`
	Tg *string `json:"TG,omitempty"`
	Tk *string `json:"TK,omitempty"`
	To *string `json:"TO,omitempty"`
	Tt *string `json:"TT,omitempty"`
	Tn *string `json:"TN,omitempty"`
	Tr *string `json:"TR,omitempty"`
	Tm *string `json:"TM,omitempty"`
	Tc *string `json:"TC,omitempty"`
	Tv *string `json:"TV,omitempty"`
	Ug *string `json:"UG,omitempty"`
	Ua *string `json:"UA,omitempty"`
	Ae *string `json:"AE,omitempty"`
	Gb *string `json:"GB,omitempty"`
	Us *string `json:"US,omitempty"`
	Um *string `json:"UM,omitempty"`
	Uy *string `json:"UY,omitempty"`
	Uz *string `json:"UZ,omitempty"`
	Vu *string `json:"VU,omitempty"`
	Ve *string `json:"VE,omitempty"`
	Vn *string `json:"VN,omitempty"`
	Vg *string `json:"VG,omitempty"`
	Vi *string `json:"VI,omitempty"`
	Wf *string `json:"WF,omitempty"`
	Eh *string `json:"EH,omitempty"`
	Ye *string `json:"YE,omitempty"`
	Zm *string `json:"ZM,omitempty"`
	Zw *string `json:"ZW,omitempty"`
	Ax *string `json:"AX,omitempty"`
	Bq *string `json:"BQ,omitempty"`
	Cw *string `json:"CW,omitempty"`
	Gg *string `json:"GG,omitempty"`
	Im *string `json:"IM,omitempty"`
	Je *string `json:"JE,omitempty"`
	Me *string `json:"ME,omitempty"`
	Bl *string `json:"BL,omitempty"`
	Mf *string `json:"MF,omitempty"`
	Rs *string `json:"RS,omitempty"`
	Sx *string `json:"SX,omitempty"`
	Ss *string `json:"SS,omitempty"`
	Xk *string `json:"XK,omitempty"`
}

func (l *LinkGeoTargeting) GetAf() *string {
	if l == nil {
		return nil
	}
	return l.Af
}

func (l *LinkGeoTargeting) GetAl() *string {
	if l == nil {
		return nil
	}
	return l.Al
}

func (l *LinkGeoTargeting) GetDz() *string {
	if l == nil {
		return nil
	}
	return l.Dz
}

func (l *LinkGeoTargeting) GetAs() *string {
	if l == nil {
		return nil
	}
	return l.As
}

func (l *LinkGeoTargeting) GetAd() *string {
	if l == nil {
		return nil
	}
	return l.Ad
}

func (l *LinkGeoTargeting) GetAo() *string {
	if l == nil {
		return nil
	}
	return l.Ao
}

func (l *LinkGeoTargeting) GetAi() *string {
	if l == nil {
		return nil
	}
	return l.Ai
}

func (l *LinkGeoTargeting) GetAq() *string {
	if l == nil {
		return nil
	}
	return l.Aq
}

func (l *LinkGeoTargeting) GetAg() *string {
	if l == nil {
		return nil
	}
	return l.Ag
}

func (l *LinkGeoTargeting) GetAr() *string {
	if l == nil {
		return nil
	}
	return l.Ar
}

func (l *LinkGeoTargeting) GetAm() *string {
	if l == nil {
		return nil
	}
	return l.Am
}

func (l *LinkGeoTargeting) GetAw() *string {
	if l == nil {
		return nil
	}
	return l.Aw
}

func (l *LinkGeoTargeting) GetAu() *string {
	if l == nil {
		return nil
	}
	return l.Au
}

func (l *LinkGeoTargeting) GetAt() *string {
	if l == nil {
		return nil
	}
	return l.At
}

func (l *LinkGeoTargeting) GetAz() *string {
	if l == nil {
		return nil
	}
	return l.Az
}

func (l *LinkGeoTargeting) GetBs() *string {
	if l == nil {
		return nil
	}
	return l.Bs
}

func (l *LinkGeoTargeting) GetBh() *string {
	if l == nil {
		return nil
	}
	return l.Bh
}

func (l *LinkGeoTargeting) GetBd() *string {
	if l == nil {
		return nil
	}
	return l.Bd
}

func (l *LinkGeoTargeting) GetBb() *string {
	if l == nil {
		return nil
	}
	return l.Bb
}

func (l *LinkGeoTargeting) GetBy() *string {
	if l == nil {
		return nil
	}
	return l.By
}

func (l *LinkGeoTargeting) GetBe() *string {
	if l == nil {
		return nil
	}
	return l.Be
}

func (l *LinkGeoTargeting) GetBz() *string {
	if l == nil {
		return nil
	}
	return l.Bz
}

func (l *LinkGeoTargeting) GetBj() *string {
	if l == nil {
		return nil
	}
	return l.Bj
}

func (l *LinkGeoTargeting) GetBm() *string {
	if l == nil {
		return nil
	}
	return l.Bm
}

func (l *LinkGeoTargeting) GetBt() *string {
	if l == nil {
		return nil
	}
	return l.Bt
}

func (l *LinkGeoTargeting) GetBo() *string {
	if l == nil {
		return nil
	}
	return l.Bo
}

func (l *LinkGeoTargeting) GetBa() *string {
	if l == nil {
		return nil
	}
	return l.Ba
}

func (l *LinkGeoTargeting) GetBw() *string {
	if l == nil {
		return nil
	}
	return l.Bw
}

func (l *LinkGeoTargeting) GetBv() *string {
	if l == nil {
		return nil
	}
	return l.Bv
}

func (l *LinkGeoTargeting) GetBr() *string {
	if l == nil {
		return nil
	}
	return l.Br
}

func (l *LinkGeoTargeting) GetIo() *string {
	if l == nil {
		return nil
	}
	return l.Io
}

func (l *LinkGeoTargeting) GetBn() *string {
	if l == nil {
		return nil
	}
	return l.Bn
}

func (l *LinkGeoTargeting) GetBg() *string {
	if l == nil {
		return nil
	}
	return l.Bg
}

func (l *LinkGeoTargeting) GetBf() *string {
	if l == nil {
		return nil
	}
	return l.Bf
}

func (l *LinkGeoTargeting) GetBi() *string {
	if l == nil {
		return nil
	}
	return l.Bi
}

func (l *LinkGeoTargeting) GetKh() *string {
	if l == nil {
		return nil
	}
	return l.Kh
}

func (l *LinkGeoTargeting) GetCm() *string {
	if l == nil {
		return nil
	}
	return l.Cm
}

func (l *LinkGeoTargeting) GetCa() *string {
	if l == nil {
		return nil
	}
	return l.Ca
}

func (l *LinkGeoTargeting) GetCv() *string {
	if l == nil {
		return nil
	}
	return l.Cv
}

func (l *LinkGeoTargeting) GetKy() *string {
	if l == nil {
		return nil
	}
	return l.Ky
}

func (l *LinkGeoTargeting) GetCf() *string {
	if l == nil {
		return nil
	}
	return l.Cf
}

func (l *LinkGeoTargeting) GetTd() *string {
	if l == nil {
		return nil
	}
	return l.Td
}

func (l *LinkGeoTargeting) GetCl() *string {
	if l == nil {
		return nil
	}
	return l.Cl
}

func (l *LinkGeoTargeting) GetCn() *string {
	if l == nil {
		return nil
	}
	return l.Cn
}

func (l *LinkGeoTargeting) GetCx() *string {
	if l == nil {
		return nil
	}
	return l.Cx
}

func (l *LinkGeoTargeting) GetCc() *string {
	if l == nil {
		return nil
	}
	return l.Cc
}

func (l *LinkGeoTargeting) GetCo() *string {
	if l == nil {
		return nil
	}
	return l.Co
}

func (l *LinkGeoTargeting) GetKm() *string {
	if l == nil {
		return nil
	}
	return l.Km
}

func (l *LinkGeoTargeting) GetCg() *string {
	if l == nil {
		return nil
	}
	return l.Cg
}

func (l *LinkGeoTargeting) GetCd() *string {
	if l == nil {
		return nil
	}
	return l.Cd
}

func (l *LinkGeoTargeting) GetCk() *string {
	if l == nil {
		return nil
	}
	return l.Ck
}

func (l *LinkGeoTargeting) GetCr() *string {
	if l == nil {
		return nil
	}
	return l.Cr
}

func (l *LinkGeoTargeting) GetCi() *string {
	if l == nil {
		return nil
	}
	return l.Ci
}

func (l *LinkGeoTargeting) GetHr() *string {
	if l == nil {
		return nil
	}
	return l.Hr
}

func (l *LinkGeoTargeting) GetCu() *string {
	if l == nil {
		return nil
	}
	return l.Cu
}

func (l *LinkGeoTargeting) GetCy() *string {
	if l == nil {
		return nil
	}
	return l.Cy
}

func (l *LinkGeoTargeting) GetCz() *string {
	if l == nil {
		return nil
	}
	return l.Cz
}

func (l *LinkGeoTargeting) GetDk() *string {
	if l == nil {
		return nil
	}
	return l.Dk
}

func (l *LinkGeoTargeting) GetDj() *string {
	if l == nil {
		return nil
	}
	return l.Dj
}

func (l *LinkGeoTargeting) GetDm() *string {
	if l == nil {
		return nil
	}
	return l.Dm
}

func (l *LinkGeoTargeting) GetDo() *string {
	if l == nil {
		return nil
	}
	return l.Do
}

func (l *LinkGeoTargeting) GetEc() *string {
	if l == nil {
		return nil
	}
	return l.Ec
}

func (l *LinkGeoTargeting) GetEg() *string {
	if l == nil {
		return nil
	}
	return l.Eg
}

func (l *LinkGeoTargeting) GetSv() *string {
	if l == nil {
		return nil
	}
	return l.Sv
}

func (l *LinkGeoTargeting) GetGq() *string {
	if l == nil {
		return nil
	}
	return l.Gq
}

func (l *LinkGeoTargeting) GetEr() *string {
	if l == nil {
		return nil
	}
	return l.Er
}

func (l *LinkGeoTargeting) GetEe() *string {
	if l == nil {
		return nil
	}
	return l.Ee
}

func (l *LinkGeoTargeting) GetEt() *string {
	if l == nil {
		return nil
	}
	return l.Et
}

func (l *LinkGeoTargeting) GetFk() *string {
	if l == nil {
		return nil
	}
	return l.Fk
}

func (l *LinkGeoTargeting) GetFo() *string {
	if l == nil {
		return nil
	}
	return l.Fo
}

func (l *LinkGeoTargeting) GetFj() *string {
	if l == nil {
		return nil
	}
	return l.Fj
}

func (l *LinkGeoTargeting) GetFi() *string {
	if l == nil {
		return nil
	}
	return l.Fi
}

func (l *LinkGeoTargeting) GetFr() *string {
	if l == nil {
		return nil
	}
	return l.Fr
}

func (l *LinkGeoTargeting) GetGf() *string {
	if l == nil {
		return nil
	}
	return l.Gf
}

func (l *LinkGeoTargeting) GetPf() *string {
	if l == nil {
		return nil
	}
	return l.Pf
}

func (l *LinkGeoTargeting) GetTf() *string {
	if l == nil {
		return nil
	}
	return l.Tf
}

func (l *LinkGeoTargeting) GetGa() *string {
	if l == nil {
		return nil
	}
	return l.Ga
}

func (l *LinkGeoTargeting) GetGm() *string {
	if l == nil {
		return nil
	}
	return l.Gm
}

func (l *LinkGeoTargeting) GetGe() *string {
	if l == nil {
		return nil
	}
	return l.Ge
}

func (l *LinkGeoTargeting) GetDe() *string {
	if l == nil {
		return nil
	}
	return l.De
}

func (l *LinkGeoTargeting) GetGh() *string {
	if l == nil {
		return nil
	}
	return l.Gh
}

func (l *LinkGeoTargeting) GetGi() *string {
	if l == nil {
		return nil
	}
	return l.Gi
}

func (l *LinkGeoTargeting) GetGr() *string {
	if l == nil {
		return nil
	}
	return l.Gr
}

func (l *LinkGeoTargeting) GetGl() *string {
	if l == nil {
		return nil
	}
	return l.Gl
}

func (l *LinkGeoTargeting) GetGd() *string {
	if l == nil {
		return nil
	}
	return l.Gd
}

func (l *LinkGeoTargeting) GetGp() *string {
	if l == nil {
		return nil
	}
	return l.Gp
}

func (l *LinkGeoTargeting) GetGu() *string {
	if l == nil {
		return nil
	}
	return l.Gu
}

func (l *LinkGeoTargeting) GetGt() *string {
	if l == nil {
		return nil
	}
	return l.Gt
}

func (l *LinkGeoTargeting) GetGn() *string {
	if l == nil {
		return nil
	}
	return l.Gn
}

func (l *LinkGeoTargeting) GetGw() *string {
	if l == nil {
		return nil
	}
	return l.Gw
}

func (l *LinkGeoTargeting) GetGy() *string {
	if l == nil {
		return nil
	}
	return l.Gy
}

func (l *LinkGeoTargeting) GetHt() *string {
	if l == nil {
		return nil
	}
	return l.Ht
}

func (l *LinkGeoTargeting) GetHm() *string {
	if l == nil {
		return nil
	}
	return l.Hm
}

func (l *LinkGeoTargeting) GetVa() *string {
	if l == nil {
		return nil
	}
	return l.Va
}

func (l *LinkGeoTargeting) GetHn() *string {
	if l == nil {
		return nil
	}
	return l.Hn
}

func (l *LinkGeoTargeting) GetHk() *string {
	if l == nil {
		return nil
	}
	return l.Hk
}

func (l *LinkGeoTargeting) GetHu() *string {
	if l == nil {
		return nil
	}
	return l.Hu
}

func (l *LinkGeoTargeting) GetIs() *string {
	if l == nil {
		return nil
	}
	return l.Is
}

func (l *LinkGeoTargeting) GetIn() *string {
	if l == nil {
		return nil
	}
	return l.In
}

func (l *LinkGeoTargeting) GetID() *string {
	if l == nil {
		return nil
	}
	return l.ID
}

func (l *LinkGeoTargeting) GetIr() *string {
	if l == nil {
		return nil
	}
	return l.Ir
}

func (l *LinkGeoTargeting) GetIq() *string {
	if l == nil {
		return nil
	}
	return l.Iq
}

func (l *LinkGeoTargeting) GetIe() *string {
	if l == nil {
		return nil
	}
	return l.Ie
}

func (l *LinkGeoTargeting) GetIl() *string {
	if l == nil {
		return nil
	}
	return l.Il
}

func (l *LinkGeoTargeting) GetIt() *string {
	if l == nil {
		return nil
	}
	return l.It
}

func (l *LinkGeoTargeting) GetJm() *string {
	if l == nil {
		return nil
	}
	return l.Jm
}

func (l *LinkGeoTargeting) GetJp() *string {
	if l == nil {
		return nil
	}
	return l.Jp
}

func (l *LinkGeoTargeting) GetJo() *string {
	if l == nil {
		return nil
	}
	return l.Jo
}

func (l *LinkGeoTargeting) GetKz() *string {
	if l == nil {
		return nil
	}
	return l.Kz
}

func (l *LinkGeoTargeting) GetKe() *string {
	if l == nil {
		return nil
	}
	return l.Ke
}

func (l *LinkGeoTargeting) GetKi() *string {
	if l == nil {
		return nil
	}
	return l.Ki
}

func (l *LinkGeoTargeting) GetKp() *string {
	if l == nil {
		return nil
	}
	return l.Kp
}

func (l *LinkGeoTargeting) GetKr() *string {
	if l == nil {
		return nil
	}
	return l.Kr
}

func (l *LinkGeoTargeting) GetKw() *string {
	if l == nil {
		return nil
	}
	return l.Kw
}

func (l *LinkGeoTargeting) GetKg() *string {
	if l == nil {
		return nil
	}
	return l.Kg
}

func (l *LinkGeoTargeting) GetLa() *string {
	if l == nil {
		return nil
	}
	return l.La
}

func (l *LinkGeoTargeting) GetLv() *string {
	if l == nil {
		return nil
	}
	return l.Lv
}

func (l *LinkGeoTargeting) GetLb() *string {
	if l == nil {
		return nil
	}
	return l.Lb
}

func (l *LinkGeoTargeting) GetLs() *string {
	if l == nil {
		return nil
	}
	return l.Ls
}

func (l *LinkGeoTargeting) GetLr() *string {
	if l == nil {
		return nil
	}
	return l.Lr
}

func (l *LinkGeoTargeting) GetLy() *string {
	if l == nil {
		return nil
	}
	return l.Ly
}

func (l *LinkGeoTargeting) GetLi() *string {
	if l == nil {
		return nil
	}
	return l.Li
}

func (l *LinkGeoTargeting) GetLt() *string {
	if l == nil {
		return nil
	}
	return l.Lt
}

func (l *LinkGeoTargeting) GetLu() *string {
	if l == nil {
		return nil
	}
	return l.Lu
}

func (l *LinkGeoTargeting) GetMo() *string {
	if l == nil {
		return nil
	}
	return l.Mo
}

func (l *LinkGeoTargeting) GetMg() *string {
	if l == nil {
		return nil
	}
	return l.Mg
}

func (l *LinkGeoTargeting) GetMw() *string {
	if l == nil {
		return nil
	}
	return l.Mw
}

func (l *LinkGeoTargeting) GetMy() *string {
	if l == nil {
		return nil
	}
	return l.My
}

func (l *LinkGeoTargeting) GetMv() *string {
	if l == nil {
		return nil
	}
	return l.Mv
}

func (l *LinkGeoTargeting) GetMl() *string {
	if l == nil {
		return nil
	}
	return l.Ml
}

func (l *LinkGeoTargeting) GetMt() *string {
	if l == nil {
		return nil
	}
	return l.Mt
}

func (l *LinkGeoTargeting) GetMh() *string {
	if l == nil {
		return nil
	}
	return l.Mh
}

func (l *LinkGeoTargeting) GetMq() *string {
	if l == nil {
		return nil
	}
	return l.Mq
}

func (l *LinkGeoTargeting) GetMr() *string {
	if l == nil {
		return nil
	}
	return l.Mr
}

func (l *LinkGeoTargeting) GetMu() *string {
	if l == nil {
		return nil
	}
	return l.Mu
}

func (l *LinkGeoTargeting) GetYt() *string {
	if l == nil {
		return nil
	}
	return l.Yt
}

func (l *LinkGeoTargeting) GetMx() *string {
	if l == nil {
		return nil
	}
	return l.Mx
}

func (l *LinkGeoTargeting) GetFm() *string {
	if l == nil {
		return nil
	}
	return l.Fm
}

func (l *LinkGeoTargeting) GetMd() *string {
	if l == nil {
		return nil
	}
	return l.Md
}

func (l *LinkGeoTargeting) GetMc() *string {
	if l == nil {
		return nil
	}
	return l.Mc
}

func (l *LinkGeoTargeting) GetMn() *string {
	if l == nil {
		return nil
	}
	return l.Mn
}

func (l *LinkGeoTargeting) GetMs() *string {
	if l == nil {
		return nil
	}
	return l.Ms
}

func (l *LinkGeoTargeting) GetMa() *string {
	if l == nil {
		return nil
	}
	return l.Ma
}

func (l *LinkGeoTargeting) GetMz() *string {
	if l == nil {
		return nil
	}
	return l.Mz
}

func (l *LinkGeoTargeting) GetMm() *string {
	if l == nil {
		return nil
	}
	return l.Mm
}

func (l *LinkGeoTargeting) GetNa() *string {
	if l == nil {
		return nil
	}
	return l.Na
}

func (l *LinkGeoTargeting) GetNr() *string {
	if l == nil {
		return nil
	}
	return l.Nr
}

func (l *LinkGeoTargeting) GetNp() *string {
	if l == nil {
		return nil
	}
	return l.Np
}

func (l *LinkGeoTargeting) GetNl() *string {
	if l == nil {
		return nil
	}
	return l.Nl
}

func (l *LinkGeoTargeting) GetNc() *string {
	if l == nil {
		return nil
	}
	return l.Nc
}

func (l *LinkGeoTargeting) GetNz() *string {
	if l == nil {
		return nil
	}
	return l.Nz
}

func (l *LinkGeoTargeting) GetNi() *string {
	if l == nil {
		return nil
	}
	return l.Ni
}

func (l *LinkGeoTargeting) GetNe() *string {
	if l == nil {
		return nil
	}
	return l.Ne
}

func (l *LinkGeoTargeting) GetNg() *string {
	if l == nil {
		return nil
	}
	return l.Ng
}

func (l *LinkGeoTargeting) GetNu() *string {
	if l == nil {
		return nil
	}
	return l.Nu
}

func (l *LinkGeoTargeting) GetNf() *string {
	if l == nil {
		return nil
	}
	return l.Nf
}

func (l *LinkGeoTargeting) GetMk() *string {
	if l == nil {
		return nil
	}
	return l.Mk
}

func (l *LinkGeoTargeting) GetMp() *string {
	if l == nil {
		return nil
	}
	return l.Mp
}

func (l *LinkGeoTargeting) GetNo() *string {
	if l == nil {
		return nil
	}
	return l.No
}

func (l *LinkGeoTargeting) GetOm() *string {
	if l == nil {
		return nil
	}
	return l.Om
}

func (l *LinkGeoTargeting) GetPk() *string {
	if l == nil {
		return nil
	}
	return l.Pk
}

func (l *LinkGeoTargeting) GetPw() *string {
	if l == nil {
		return nil
	}
	return l.Pw
}

func (l *LinkGeoTargeting) GetPs() *string {
	if l == nil {
		return nil
	}
	return l.Ps
}

func (l *LinkGeoTargeting) GetPa() *string {
	if l == nil {
		return nil
	}
	return l.Pa
}

func (l *LinkGeoTargeting) GetPg() *string {
	if l == nil {
		return nil
	}
	return l.Pg
}

func (l *LinkGeoTargeting) GetPy() *string {
	if l == nil {
		return nil
	}
	return l.Py
}

func (l *LinkGeoTargeting) GetPe() *string {
	if l == nil {
		return nil
	}
	return l.Pe
}

func (l *LinkGeoTargeting) GetPh() *string {
	if l == nil {
		return nil
	}
	return l.Ph
}

func (l *LinkGeoTargeting) GetPn() *string {
	if l == nil {
		return nil
	}
	return l.Pn
}

func (l *LinkGeoTargeting) GetPl() *string {
	if l == nil {
		return nil
	}
	return l.Pl
}

func (l *LinkGeoTargeting) GetPt() *string {
	if l == nil {
		return nil
	}
	return l.Pt
}

func (l *LinkGeoTargeting) GetPr() *string {
	if l == nil {
		return nil
	}
	return l.Pr
}

func (l *LinkGeoTargeting) GetQa() *string {
	if l == nil {
		return nil
	}
	return l.Qa
}

func (l *LinkGeoTargeting) GetRe() *string {
	if l == nil {
		return nil
	}
	return l.Re
}

func (l *LinkGeoTargeting) GetRo() *string {
	if l == nil {
		return nil
	}
	return l.Ro
}

func (l *LinkGeoTargeting) GetRu() *string {
	if l == nil {
		return nil
	}
	return l.Ru
}

func (l *LinkGeoTargeting) GetRw() *string {
	if l == nil {
		return nil
	}
	return l.Rw
}

func (l *LinkGeoTargeting) GetSh() *string {
	if l == nil {
		return nil
	}
	return l.Sh
}

func (l *LinkGeoTargeting) GetKn() *string {
	if l == nil {
		return nil
	}
	return l.Kn
}

func (l *LinkGeoTargeting) GetLc() *string {
	if l == nil {
		return nil
	}
	return l.Lc
}

func (l *LinkGeoTargeting) GetPm() *string {
	if l == nil {
		return nil
	}
	return l.Pm
}

func (l *LinkGeoTargeting) GetVc() *string {
	if l == nil {
		return nil
	}
	return l.Vc
}

func (l *LinkGeoTargeting) GetWs() *string {
	if l == nil {
		return nil
	}
	return l.Ws
}

func (l *LinkGeoTargeting) GetSm() *string {
	if l == nil {
		return nil
	}
	return l.Sm
}

func (l *LinkGeoTargeting) GetSt() *string {
	if l == nil {
		return nil
	}
	return l.St
}

func (l *LinkGeoTargeting) GetSa() *string {
	if l == nil {
		return nil
	}
	return l.Sa
}

func (l *LinkGeoTargeting) GetSn() *string {
	if l == nil {
		return nil
	}
	return l.Sn
}

func (l *LinkGeoTargeting) GetSc() *string {
	if l == nil {
		return nil
	}
	return l.Sc
}

func (l *LinkGeoTargeting) GetSl() *string {
	if l == nil {
		return nil
	}
	return l.Sl
}

func (l *LinkGeoTargeting) GetSg() *string {
	if l == nil {
		return nil
	}
	return l.Sg
}

func (l *LinkGeoTargeting) GetSk() *string {
	if l == nil {
		return nil
	}
	return l.Sk
}

func (l *LinkGeoTargeting) GetSi() *string {
	if l == nil {
		return nil
	}
	return l.Si
}

func (l *LinkGeoTargeting) GetSb() *string {
	if l == nil {
		return nil
	}
	return l.Sb
}

func (l *LinkGeoTargeting) GetSo() *string {
	if l == nil {
		return nil
	}
	return l.So
}

func (l *LinkGeoTargeting) GetZa() *string {
	if l == nil {
		return nil
	}
	return l.Za
}

func (l *LinkGeoTargeting) GetGs() *string {
	if l == nil {
		return nil
	}
	return l.Gs
}

func (l *LinkGeoTargeting) GetEs() *string {
	if l == nil {
		return nil
	}
	return l.Es
}

func (l *LinkGeoTargeting) GetLk() *string {
	if l == nil {
		return nil
	}
	return l.Lk
}

func (l *LinkGeoTargeting) GetSd() *string {
	if l == nil {
		return nil
	}
	return l.Sd
}

func (l *LinkGeoTargeting) GetSr() *string {
	if l == nil {
		return nil
	}
	return l.Sr
}

func (l *LinkGeoTargeting) GetSj() *string {
	if l == nil {
		return nil
	}
	return l.Sj
}

func (l *LinkGeoTargeting) GetSz() *string {
	if l == nil {
		return nil
	}
	return l.Sz
}

func (l *LinkGeoTargeting) GetSe() *string {
	if l == nil {
		return nil
	}
	return l.Se
}

func (l *LinkGeoTargeting) GetCh() *string {
	if l == nil {
		return nil
	}
	return l.Ch
}

func (l *LinkGeoTargeting) GetSy() *string {
	if l == nil {
		return nil
	}
	return l.Sy
}

func (l *LinkGeoTargeting) GetTw() *string {
	if l == nil {
		return nil
	}
	return l.Tw
}

func (l *LinkGeoTargeting) GetTj() *string {
	if l == nil {
		return nil
	}
	return l.Tj
}

func (l *LinkGeoTargeting) GetTz() *string {
	if l == nil {
		return nil
	}
	return l.Tz
}

func (l *LinkGeoTargeting) GetTh() *string {
	if l == nil {
		return nil
	}
	return l.Th
}

func (l *LinkGeoTargeting) GetTl() *string {
	if l == nil {
		return nil
	}
	return l.Tl
}

func (l *LinkGeoTargeting) GetTg() *string {
	if l == nil {
		return nil
	}
	return l.Tg
}

func (l *LinkGeoTargeting) GetTk() *string {
	if l == nil {
		return nil
	}
	return l.Tk
}

func (l *LinkGeoTargeting) GetTo() *string {
	if l == nil {
		return nil
	}
	return l.To
}

func (l *LinkGeoTargeting) GetTt() *string {
	if l == nil {
		return nil
	}
	return l.Tt
}

func (l *LinkGeoTargeting) GetTn() *string {
	if l == nil {
		return nil
	}
	return l.Tn
}

func (l *LinkGeoTargeting) GetTr() *string {
	if l == nil {
		return nil
	}
	return l.Tr
}

func (l *LinkGeoTargeting) GetTm() *string {
	if l == nil {
		return nil
	}
	return l.Tm
}

func (l *LinkGeoTargeting) GetTc() *string {
	if l == nil {
		return nil
	}
	return l.Tc
}

func (l *LinkGeoTargeting) GetTv() *string {
	if l == nil {
		return nil
	}
	return l.Tv
}

func (l *LinkGeoTargeting) GetUg() *string {
	if l == nil {
		return nil
	}
	return l.Ug
}

func (l *LinkGeoTargeting) GetUa() *string {
	if l == nil {
		return nil
	}
	return l.Ua
}

func (l *LinkGeoTargeting) GetAe() *string {
	if l == nil {
		return nil
	}
	return l.Ae
}

func (l *LinkGeoTargeting) GetGb() *string {
	if l == nil {
		return nil
	}
	return l.Gb
}

func (l *LinkGeoTargeting) GetUs() *string {
	if l == nil {
		return nil
	}
	return l.Us
}

func (l *LinkGeoTargeting) GetUm() *string {
	if l == nil {
		return nil
	}
	return l.Um
}

func (l *LinkGeoTargeting) GetUy() *string {
	if l == nil {
		return nil
	}
	return l.Uy
}

func (l *LinkGeoTargeting) GetUz() *string {
	if l == nil {
		return nil
	}
	return l.Uz
}

func (l *LinkGeoTargeting) GetVu() *string {
	if l == nil {
		return nil
	}
	return l.Vu
}

func (l *LinkGeoTargeting) GetVe() *string {
	if l == nil {
		return nil
	}
	return l.Ve
}

func (l *LinkGeoTargeting) GetVn() *string {
	if l == nil {
		return nil
	}
	return l.Vn
}

func (l *LinkGeoTargeting) GetVg() *string {
	if l == nil {
		return nil
	}
	return l.Vg
}

func (l *LinkGeoTargeting) GetVi() *string {
	if l == nil {
		return nil
	}
	return l.Vi
}

func (l *LinkGeoTargeting) GetWf() *string {
	if l == nil {
		return nil
	}
	return l.Wf
}

func (l *LinkGeoTargeting) GetEh() *string {
	if l == nil {
		return nil
	}
	return l.Eh
}

func (l *LinkGeoTargeting) GetYe() *string {
	if l == nil {
		return nil
	}
	return l.Ye
}

func (l *LinkGeoTargeting) GetZm() *string {
	if l == nil {
		return nil
	}
	return l.Zm
}

func (l *LinkGeoTargeting) GetZw() *string {
	if l == nil {
		return nil
	}
	return l.Zw
}

func (l *LinkGeoTargeting) GetAx() *string {
	if l == nil {
		return nil
	}
	return l.Ax
}

func (l *LinkGeoTargeting) GetBq() *string {
	if l == nil {
		return nil
	}
	return l.Bq
}

func (l *LinkGeoTargeting) GetCw() *string {
	if l == nil {
		return nil
	}
	return l.Cw
}

func (l *LinkGeoTargeting) GetGg() *string {
	if l == nil {
		return nil
	}
	return l.Gg
}

func (l *LinkGeoTargeting) GetIm() *string {
	if l == nil {
		return nil
	}
	return l.Im
}

func (l *LinkGeoTargeting) GetJe() *string {
	if l == nil {
		return nil
	}
	return l.Je
}

func (l *LinkGeoTargeting) GetMe() *string {
	if l == nil {
		return nil
	}
	return l.Me
}

func (l *LinkGeoTargeting) GetBl() *string {
	if l == nil {
		return nil
	}
	return l.Bl
}

func (l *LinkGeoTargeting) GetMf() *string {
	if l == nil {
		return nil
	}
	return l.Mf
}

func (l *LinkGeoTargeting) GetRs() *string {
	if l == nil {
		return nil
	}
	return l.Rs
}

func (l *LinkGeoTargeting) GetSx() *string {
	if l == nil {
		return nil
	}
	return l.Sx
}

func (l *LinkGeoTargeting) GetSs() *string {
	if l == nil {
		return nil
	}
	return l.Ss
}

func (l *LinkGeoTargeting) GetXk() *string {
	if l == nil {
		return nil
	}
	return l.Xk
}
