// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type Ids struct {
	Str        types.String   `queryParam:"inline" tfsdk:"str" tfPlanOnly:"true"`
	ArrayOfStr []types.String `queryParam:"inline" tfsdk:"array_of_str" tfPlanOnly:"true"`
}
